### ISSUE TITLE
Delete unintentional record for user in production interface

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#567] opened 2016-02-01 20:01 UTC
A user wrote in the following:

"Someone in our lab was interested to see what the ClinGen user interface looks like, so I logged into the production interface, typed in TNNC1, and forgot it creates a permanent record.  Is there a way to delete that record?  Sorry for the mistake on my part."

Here is the record:
https://curation.clinicalgenome.org/curation-central/?gdm=87c15ba4-1efe-4970-8cad-edca6d57d3b2

**Comment by kilodalton** [comment] 2016-02-01 22:28
#### Note: There are actually _two_  errant GDMs that need to be deleted in production as part of this task. 

 (this one mentioned above, and a second [see KD for more info])

**Comment by kilodalton** [comment] 2016-02-02 08:38
The 2 erroneous  gdms (and in the second case which also had an annotation object) have been marked as deleted and will not be shown to curators.
@selinad @wrightmw Please confirm at: https://curation.clinicalgenome.org/gdm/

**Comment by wrightmw** [comment] 2016-02-02 16:39
@kilodalton I can confirm, they have been deleted :-)

**Comment by selinad** [comment] 2016-02-02 17:06
I cannot see them either!  Thanks so much, @kilodalton.  I will write the user back to let him know it's been resolved.

**Comment by kilodalton** [comment] 2016-02-02 22:05
I realized there may be an outstanding history item that would still show on a user's dashboard I think (history item that shows that GDM created). If so, should that be removed as well?  We do not have a method to indicate that a GDM has been deleted.

**Comment by kilodalton** [comment] 2016-02-05 10:38
That history item above was changed to be hidden (will not display on curator's dashboard) since we don't have a corresponding history item to indicate the accidentally-created GDM has been marked as deleted.

**Closed** 2016-02-05 10:38 UTC
Labels: curator review, external curator, priority: high, R4, urgent
