### ISSUE TITLE
Copy disease from Associated Family button appears after deleting disease from proband when no Family disease existed

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1375] opened 2017-06-14 21:18 UTC
If I create a Family w/no disease, and add a proband (with a disease) while entering Family, then go to that proband to edit and then delete the disease from that proband, I get this:
![screen shot 2017-06-14 at 2 08 15 pm](https://user-images.githubusercontent.com/11320314/27155057-2de26008-510c-11e7-80af-f83e7461b776.png)

This is not a show stopper.  Nothing freezes and curator ok to add another disease.  For R12, add logic that doesn't display the Copy button (much like it's not displayed within Family page when creating a proband if there is no disease associated with Family

**Comment by jimmyzhen** [comment] 2017-07-27 22:45
Hi @selinad,

You may review the requested changes in the following instance:
https://1301-jz-family-curation-9d2b384-jzhen.demo.clinicalgenome.org

With the changes in question, instead of not showing a `Copy` button at all, I tried showing the `Copy disease term from Gene-Disease Record` button if the individual's associated family has _no_ disease or the individual has _no_ associated group.

Let me know whether this would work. Thanks!

**Comment by selinad** [comment] 2017-08-01 00:32
@jimmyzhen it works great!  Excellent.  

To clarify, currently an Individual with no group or family behaves this way in the interface already, correct?

**Comment by jimmyzhen** [comment] 2017-08-01 00:35
Yes, @selinad.

**Comment by wrightmw** [comment] 2017-08-01 00:49
@jimmyzhen Works for me!

**Comment by jimmyzhen** [comment] 2017-08-03 00:30
Hi @selinad, @wrightmw,

I discovered a bug in the process of testing my PR for this ticket.

When creating a new Family curation (with or without adding a disease to the family), the associated disease for the Proband actually didn't get saved properly for the Proband **if the disease is not already in the (test) database**.

I have since addressed the bug and committed the changes to the PR. I am also spinning up a new instance so that you can verify the changes indeed working as expected.

The following instance shall be ready for testing in about 30 minutes:
https://1301-jz-family-curation-67cd07b-jzhen.demo.clinicalgenome.org

**Comment by selinad** [comment] 2017-08-05 00:45
I tried this by creating a Family (copying disease from record) and while on the Family page added a proband and the disease Orphanet:228184.  It saved well (there when I went to the proband).  Let me know if that was the correct way to test.

Good catch!

**Comment by jimmyzhen** [comment] 2017-08-05 00:51
@selinad: Correct, that is the expected behavior. Thanks!

**Comment by wrightmw** [comment] 2017-08-05 00:54
And I concur that it is fixed! Thanks @jimmyzhen

**Comment by selinad** [comment] 2017-08-29 22:12
@jimmyzhen All is fixed!  thank you!

**Comment by wrightmw** [comment] 2017-08-30 00:45
Great @jimmyzhen

**Closed** 2017-09-07 20:53 UTC
Labels: bug, gene curation interface, R12, release ready
