### ISSUE TITLE
Create Case-Control Curation page

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#1074] opened 2016-10-12 22:16 UTC
Create a page for curating Case-Control information.  

It will allow the following:
- Entry of Case Cohort information
- Entry of Control Cohort information
- Entry of Case-Control Evaluation/Scoring information

For now, we should use the following sections on the current Group page as a template for both Case Cohort and Control Cohort:
- Label for Case Cohort or Control Cohort
- Diseases (_Case Cohort only_)
- Demographics (both)
- Group info (both)
- Methods (both)
- Additional info (both)

We will remove fields for the Group info section and relabel to Case Cohort or Control Cohort wherever appropriate.

Could be side-by-side or vertical....

There is a preliminary wireframe in Asana.

**Comment by jimmyzhen** [comment] 2016-10-19 17:54
Hi all,

I have an instance spun up to give you a snapshot of what I have so far:
https://1074-jz-case-control-page-ae33ea7-jzhen.demo.clinicalgenome.org

At the moment for this instance, I have only implemented most of the expected UIs. I have not wired up everything yet, including the logic to submit the form and/or display pre-existing form data. But I do wish you all can review the UIs and give me some feedback.

**Note:** To access the Case-Control page, go to Curation Central and click on the **Case-Control** bar in the Curation Palette.

**Comment by kgliu0101** [comment] 2016-10-19 19:10
@jimmyzhen Great one.

In control cohort Power, field "Enter numeric value of all Cases genotyped/sequenced" should be "... of all Controls ...". And, it looks to me that next field "Case Allele Frequency" should be "Control Allele Frequency", but not sure. Need to be confirmed by curators.

**Comment by jimmyzhen** [comment] 2016-10-19 19:27
Thank you, @kgliu0101!

**Comment by jimmyzhen** [comment] 2016-10-21 01:09
Hi @selinad, @wrightmw, @kilodalton,

Currently, we display the user-provided group label right above the **Group** panel. In the case of the Case-Control page which has 2 **Group** panels, how do we want this UI to behave?

![image](https://cloud.githubusercontent.com/assets/6956310/19583299/47cae872-96f0-11e6-9a43-1498e6718bdc.png)

**Comment by selinad** [comment] 2016-10-25 00:35
Hi @jimmyzhen - as mentioned in person, we should have a Case-Control section that spans both the Case Cohort and Control Cohort and allows a user to enter a label for the Case-Control.

As far as representing the labels, maybe we could do the following:

[Record icon] // Case-Control label (Case: label; Control: label)
e.g.
[Record icon] // Study 5 (Case: MYH7 group; Control: matched population)

**Comment by wrightmw** [comment] 2016-10-25 00:58
@jimmyzhen This is looking great!

I agree with entering a label for 'CaseCohort-ControlCohort'... and this should be the title for the whole group

**Comment by selinad** [comment] 2016-10-25 01:05
Hi @jimmyzhen 

Such great work. Thank you.  Here are my comments as I go through:

### Front page styling
I like the Case Level and Case-Control gray images.  One quick thing - they grab my eye more than the text in blue, though, and I miss the 2 bigger categories (Genetic Evidence and Experimental).  Also, blue text often means a hyperlink - could we maybe make that text black and not italic?  The font size seems good. Same comment on Case-Control page with blue text (not urgent!)/

![screen shot 2016-10-24 at 5 42 05 pm](https://cloud.githubusercontent.com/assets/11320314/19669080/3f27a7cc-9a11-11e6-8225-2639d4da80ef.png)


### Section for entering Case-Control label
We talked about this in person, but will write it down so it's recorded - have it span the 2 cohorts and have a place to enter label ( @kgliu0101 also knows) - see earlier comment for how labels displayed

### Previous testing
@wrightmw - I'm realizing we probably don't need "Previous testing" for the Control group - do you agree?  We can send this along for feedback from the group or give RG access to the instance.

### Power
- replace the word "Cases" with "Controls" in all 3 questions (e.g. "Enter numeric value of **Controls** with variant(s):"

**Comment by wrightmw** [comment] 2016-10-25 01:29
I would change 'Experimental' to 'Experimental Evidence'

**Comment by jimmyzhen** [comment] 2016-10-25 19:07
Hi @selinad, @wrightmw,

I have the following new instance for you to review the UI changes we discussed yesterday:
https://1074-jz-case-control-page-aba822e-jzhen.demo.clinicalgenome.org

Please feel free to share with RG as well if needed. Thanks.

**Comment by selinad** [comment] 2016-10-25 19:14
Great - thanks, @jimmyzhen !

**Comment by selinad** [comment] 2016-10-25 19:38
@jimmyzhen just opened it up, but I already have to say great job! on the UI for the Record page (genetic evidence vs. experimental).  @wrightmw - do you think a mouse icon would work for experimental?

**Comment by selinad** [comment] 2016-10-25 19:41
@jimmyzhen also love the headers on the case-control page itself - really nice job.  

I've sent it along to Raj - we need his feedback to make certain we spec'd all fields correctly.  Will report back.

thx again - great work!

**Comment by selinad** [comment] 2016-10-25 19:43
@wrightmw I just thought of one things for now - we could add "(Case)" or "(Control)" to each header on the Case-control page (except Disease/pheno one) - while not a different color, it would give quick reference since the page is long.....

**Comment by wrightmw** [comment] 2016-10-25 19:51
@jimmyzhen Great work! I like it, a lot.

**Comment by wrightmw** [comment] 2016-10-25 19:52
@selinad ... there are lots of other models used, other than mice.. how about a conical flask?

**Comment by selinad** [comment] 2016-10-25 19:54
hehe.  yep, as thinking a mouse was a fair catch-all.  I'll take a look on font awesome - flask seems in vitro to me

**Comment by wrightmw** [comment] 2016-10-25 19:56
Yeah... could always use DNA?

**Comment by jimmyzhen** [comment] 2016-10-25 20:03
Flask: http://fontawesome.io/icon/flask/

**Comment by selinad** [comment] 2016-10-25 20:04
DNA might imply sequencing.  I'd say a mouse or a cell - not sure where to find those icons...

ok - flask not bad!

**Comment by wrightmw** [comment] 2016-10-25 20:06
@selinad Only one of the six experiment types is animal models and even these are often not in mouse.  Whereas I think a flask is a generic icon for all experiments.

**Comment by selinad** [comment] 2016-10-25 20:09
I think it's a question of what brings experimental type of evidence to mind.  For me, it's a mouse for this type of evidence (could even be mouse cells), but I'm not opposed to a flask (even though _none_ are done in a flask ;-))

**Comment by jimmyzhen** [comment] 2016-10-25 20:12
How's this?

![image](https://cloud.githubusercontent.com/assets/6956310/19702463/a58138b4-9ab4-11e6-9442-3c780fda32fa.png)

**Comment by selinad** [comment] 2016-10-25 20:17
Hi @jimmyzhen - thx, it works!  I still cast my vote for a mouse or an animal cell (this type of evidence is really functional evidence about the protein), but if not easily accessible, the flask gets the message out!

![screen shot 2016-10-25 at 1 16 11 pm](https://cloud.githubusercontent.com/assets/11320314/19702637/4dfdd65a-9ab5-11e6-829f-1d5031c6f156.png)

**Comment by wrightmw** [comment] 2016-10-25 20:19
@selinad I do think that with the page being long there should be something that shows you one side is case and the other control as you scroll down. I think it would be good if we added "(Case)" or "(Control)" to each header on the Case-control page.

**Comment by jimmyzhen** [comment] 2016-10-25 20:31
There isn't a mouse icon readily available in Font Awesome, so we may need to look into other stock icons or create one ourselves (which I don't mind doing at a later time).

**Comment by selinad** [comment] 2016-10-25 20:37
thx @jimmyzhen flask is fine for now :)  We'll see if anyone objects or has better idea.

**Comment by jimmyzhen** [comment] 2016-10-25 21:09
How's this styling to label the "Case" or "Control" sections?

![image](https://cloud.githubusercontent.com/assets/6956310/19704482/ac433f82-9abc-11e6-9727-a1a8a45de786.png)

**Comment by wrightmw** [comment] 2016-10-25 22:12
@jimmyzhen It looks fine to me.

**Comment by selinad** [comment] 2016-10-25 22:30
Oops - saw @wrightmw 's comment and realized I never sent:

Looks great! Super idea, @jimmyzhen! This could be a place where the color (orange) could be slightly different for case v control - wouldn't even mind that dark gray for control (color implies case, I think)...

**Comment by wrightmw** [comment] 2016-10-25 22:48
@selinad well, as you know, I am in favour of a colour differentiator between case and control... so I support your suggestion.

**Comment by selinad** [comment] 2016-10-25 22:49
👍  I suggested with you in mind @wrightmw !

**Comment by jimmyzhen** [comment] 2016-10-25 23:54
How's this?

![image](https://cloud.githubusercontent.com/assets/6956310/19708477/acc66616-9ad3-11e6-990d-c55e4ab8f6ae.png)

**Comment by selinad** [comment] 2016-10-25 23:55
Super sweet. :-)

**Comment by jimmyzhen** [comment] 2016-10-27 22:25
Hi @selinad, @wrightmw,

What changes would you want to apply to the intermediate page?

![image](https://cloud.githubusercontent.com/assets/6956310/19787818/a0789c8a-9c59-11e6-8ab4-d2b935e1d6ab.png)

**Comment by selinad** [comment] 2016-10-27 23:35
Hi @jimmyzhen Here are comments from Raj + 1 from me:

- Enter phenotypes that are NOT present in Group if they are specifically noted in the paper. => change "Group" to "Case Cohort"
- For Control Cohort - could have this in an equivalent Diseases and phenotypes section:<br>
Healthy controls? Yes/No pull-down <br>
If no, please explain: free text box
- in Power section, should read "variants in the gene in question" rather than "variants," for both Case and Control cohorts
- Under Statistics: change "value type" to "test statistic"
- for confidence significance - remove "%" from p-value

I have 2 follow-up questions I need to ask him.

**Comment by selinad** [comment] 2016-10-27 23:53
Re the intermediate page:  Probands counted in Case-control would not be counted in Case (Family/Individual), so I am pretty certain we don't need an intermediate page ( @wrightmw do you agree?).

**Comment by wrightmw** [comment] 2016-10-28 00:00
@selinad I agree. No intermediate page. We don't want double counting of probands.

**Comment by jimmyzhen** [comment] 2016-10-28 02:48
Hi @selinad, @wrightmw,

Here is the new instance for you to review the Case-Control page:
https://1074-jz-case-control-page-c25c74b-jzhen.demo.clinicalgenome.org

**Known issues at the moment:**
1) After saving the Case-Control page, returning to the Curation-Central page appears to be working as expected. However, returning to the Dashboard page would cause errors in which the histories are not loading as expected.
2) The Case-Control statistics input fields currently expect numeric values. Errors may occur if no values or string values are entered. Need to add validation for those fields.

**Comment by selinad** [comment] 2016-10-28 03:39
Hi @jimmyzhen a very quick look looks great!

only a couple of things:
- allele frequency fields are grayed out and inactive (should be active)
- unable to delete a case-control using delete button
- as you mention, I get a spinning wheel for history.

Super job!  I'll pound on it a bit more (in a bit)

**Comment by selinad** [comment] 2016-10-28 05:49
Hi @jimmyzhen - looking at it again, I think "Numeric value of ..." should be changed to "Number of..." in all locations (e.g. Number of Cases with variants in the gene of question")

Most recent changes from Raj:
- For the power section, do you mean say "Numeric value of Cases with variant(s) in the gene in question"? (for both case and control) Answer: Yes.
- Should we use the example from IBD exomes somewhere? Answer: I just gave that as an example of how they display case control data with allele frequencies in cases and controls. More of a guide (we can add this in later)
- Would you ever have a case or control cohort where they could have variants in found in another gene during the study?  That would be what the additional info question "# individuals with variant found in other gene" would be about.... Answer:I don't think this situation will arise. I haven't seen any examples.
- Statistics section: should we remove "Other" category?  Not sure what is meant by just keep the most common one: OR. Answer: I meant that just keep OR,RR and the "other" category in the dropdown. 

Action items based on above:
- Remove  "# individuals with variant found in other gene" fields and the box for adding the gene for both case and control (suppress) - if not quick, can remove next release
- suppress everything but OR, RR and Other on pull-down for statistics

**Comment by selinad** [comment] 2016-10-28 05:52
Was not able to submit (spinning wheel) - I had filled out most of Case, but not cohort or evaluation section:
<img width="1432" alt="screen shot 2016-10-27 at 10 50 30 pm" src="https://cloud.githubusercontent.com/assets/11320314/19796263/e552a984-9c97-11e6-97a1-48ac83942254.png">

**Comment by wrightmw** [comment] 2016-10-28 05:54
@selinad I just had the same experience. Unable to submit... had spinning wheel.

**Comment by selinad** [comment] 2016-10-28 05:54
@jimmyzhen had this same problem when I started again.

**Comment by selinad** [comment] 2016-10-28 05:54
oops - thx @wrightmw .  Do you know what caused it?  I'm not exactly sure what I did.

**Comment by wrightmw** [comment] 2016-10-28 05:56
I just went through and filled in most fields and when I went to save I got a spinning wheel.

**Comment by jimmyzhen** [comment] 2016-10-28 16:16
The spinning wheel is most likely caused by certain missing form validations. I will look into it.

**Comment by jimmyzhen** [comment] 2016-10-28 23:19
Hi @selinad, @wrightmw,

I have addressed the changes you described above, as well as the bugs you experienced in the previous instance (e.g. spinning wheel, failed deletion, dashboard history). I will spin up a new instance shortly for you to review again.

**Comment by jimmyzhen** [comment] 2016-10-29 09:52
Hi @selinad, @wrightmw,

Below is the new instance for you to review:
https://1074-jz-case-control-page-045a7f6-jzhen.demo.clinicalgenome.org

Sorry for taking this long to have it ready :(

In addition to include the addition of a Case-Control to the history on the Dashboard, I also needed to include the modification and deletion of a Case-Control to the history on the Dashboard (as I realized later on).

Furthermore, upon adding a Case-Control to the history, I realized that the links in the histories would take the user to the Case-Control view page. Since suppressing the links in the histories would seem to defeat the purpose of the having the histories, so I went ahead and created the Case-Control view page. It is not pretty, but it works. As a result, the "View" link for the Case-Control in the CurationPalette is now reinstated.

Feel free to give me your feedback after reviewing the instance. Thanks!

**Comment by selinad** [comment] 2016-10-29 15:18
Wow!  Thanks @jimmyzhen - taking a look now. 
btw, REVEL back up on this instance (thx for sending email @wrightmw )

**Comment by selinad** [comment] 2016-10-29 15:37
HI @jimmyzhen looking great!  No spinning wheel so far; will try a few more entries.

Here are a few hopefully simple things:
### Change "Group" to appropriate word (sorry for not catching this before) for both Case and Control sections - see "Group" used in 2 fields below:
<img width="510" alt="screen shot 2016-10-29 at 8 22 48 am" src="https://cloud.githubusercontent.com/assets/11320314/19830677/a2fff724-9db1-11e6-91e3-a2344f6386c1.png">

### Suppress field
From earlier comments: "Remove "# individuals with variant found in other gene" fields and the box for adding the gene for both case and control (suppress) - if not quick, can remove next release"  This field is still showing (see first entry in above image)- is it easy to suppress?  If not, no worries - just double-checking.

### ORPHA number now showing on View page
Wow - the View page is great!  Thank you.  Noticed the ORPHA ID is not showing in link and that link is not functional
<img width="574" alt="screen shot 2016-10-29 at 8 26 08 am" src="https://cloud.githubusercontent.com/assets/11320314/19830704/31c1413e-9db2-11e6-803b-c2a293a9dbff.png">

### "none" when there is no selection - I'm wondering if "none" is a little misleading when a field has not been selected in a pull-down; it looks like we might just leave blank for current "Group" entries? https://1074-jz-case-control-page-045a7f6-jzhen.demo.clinicalgenome.org/groups/638aa802-5db4-41ac-87e3-45e6de7ddd4b/

<img width="620" alt="screen shot 2016-10-29 at 8 26 31 am" src="https://cloud.githubusercontent.com/assets/11320314/19830716/75de7788-9db2-11e6-8714-d21d30344b95.png">

Thanks for all of your hard work @jimmyzhen !  This is a big step towards the GCI rework.

**Comment by selinad** [comment] 2016-10-29 15:41
p.s. History looks great too!  Works well linking to View

One thing I noticed - the current View for Group has the header below, but the Case-Control View does not - would this be quick to include?
<img width="875" alt="screen shot 2016-10-29 at 8 40 21 am" src="https://cloud.githubusercontent.com/assets/11320314/19830929/7f2f7688-9db3-11e6-8608-3aca4ab20089.png">

**Comment by selinad** [comment] 2016-10-29 16:11
@jimmyzhen - curators will need to enter frequency values, etc. that are decimals - currently, it looks like many of the fields where a number can be entered do not allow decimals.
<img width="822" alt="screen shot 2016-10-29 at 9 08 05 am" src="https://cloud.githubusercontent.com/assets/11320314/19831137/8eecbbfe-9db7-11e6-9678-d549b9b928ba.png">
<img width="1086" alt="screen shot 2016-10-29 at 9 08 19 am" src="https://cloud.githubusercontent.com/assets/11320314/19831136/8ee88296-9db7-11e6-9134-646389d03465.png">

I can clarify with Raj which fields will need to allow decimals and how many places should be allowed.

**Comment by jimmyzhen** [comment] 2016-10-29 21:17
Hi @selinad:

Regarding to what you said above about suppressing "# individuals with variant found in other gene", are you referring to the following (as shown in Case-Level Group)?

![image](https://cloud.githubusercontent.com/assets/6956310/19832796/2b563f22-9de2-11e6-84e8-f589f5d42727.png)

If so, I don't think it is currently present on the Case-Control page.

**Comment by jimmyzhen** [comment] 2016-10-29 21:26
Hi @selinad, @wrightmw,

Would you also want to edit the following note in the "Additional Information" section on the Case-Control page?

![image](https://cloud.githubusercontent.com/assets/6956310/19832853/aa32df3e-9de3-11e6-8ad8-e0752bfbdf61.png)

The mentioning of family and individual may not apply in this regard. Thanks!

**Comment by selinad** [comment] 2016-10-29 21:54
Good catch Jimmy!  We do not need that note. As for the two fields you showed, I am on my phone so I will have to double check later. If those are not there than that is good. Thank you!

**Comment by jimmyzhen** [comment] 2016-10-29 22:02
The label **"Other genes found to have variants in them (HGNC symbol):"** and its input field are currently present in the **"Additional Information"** section (as shown in your and my screenshots). I can remove it if it is not needed.

**Comment by selinad** [comment] 2016-10-30 00:49
Thanks, @jimmyzhen sorry about that.  Here's what I think would be best - can you suppress the question about family ((1st question below) for Case and Control and the one about other genes (2nd question below) for Control only - if that's too difficult, let's just suppress it for both for now. 

<img width="546" alt="screen shot 2016-10-29 at 5 41 17 pm" src="https://cloud.githubusercontent.com/assets/11320314/19833664/1d70a6b4-9dff-11e6-8a73-78bacb844fd0.png">

Also, I did a 'find' for the word "Group" on the page and it's present quite a few times (see yellow).  Could you change Group to either Case Cohort or Control Cohort, depending on panel?  The above image shows 2 examples.  If you'd like me to identify all of them for you, I can.

thanks @jimmyzhen !

**Comment by selinad** [comment] 2016-10-30 00:52
The other place Group appears is under the text about providing a label.

While replacing, we use "#" for males and females -- while replacing Group, could you also change to "Number of" for both of those for both case and control?  thx!

**Comment by selinad** [comment] 2016-10-31 19:27
Hi @jimmyzhen 

I forwarded you email from Raj and we talked, but to put down on the ticket:
- text box for "Other" not showing (for OR/RR/Other pull-down)
- make the following entries allow decimals: The statistics section (value and p-value and CI)  and the allele frequency may have decimal . Rounding to one decimal places should be fine.
- working on the new title for Disease section according to Raj's comments: "Instead of common disease maybe it is better to ask what disease was this case control study designed for (or something similar)?"
- it looks GREAT!

**Comment by selinad** [comment] 2016-10-31 19:53
@jimmyzhen 

Curators said please change title to "Disease(s) and Phenotype(s)" (i.e. remove the word "Common"). 

Question - would it be easy to remove "Common" from the title for Group that is used for Case Level also ? If not, we will get it next go-round.  thx!

**Comment by jimmyzhen** [comment] 2016-10-31 21:08
Hi @selinad, @wrightmw,

I have spun up a new instance for you to review the latest changes:
https://1074-jz-case-control-page-2652926-jzhen.demo.clinicalgenome.org/

This instance is only missing the **"Disease(s) and Phenotype(s)"** change since the instance was created prior to receiving the changed text. However, I have already included the text change in the PR I've just created for this ticket.

(Note: I can remove "Common" from the title for Group that is used for Case Level also.)

**Comment by selinad** [comment] 2016-10-31 22:08
HI @jimmyzhen thx!

Looking very close - a few things:

- Some fields say e.g. number only and some say Number only...is there a reason behind this?  If not, switch all to Number only (or "Numerical value only")
- for "Other test statistic" field (now showing -perfect) - it is asking for a number, but this should be free text
- When someone types a decimal value (e.g.41.3) into a field that can only take digits, it gives an error - maybe the error should say "non-decimal values only" or something like that right now it says "Number only"
- one last thing that would be good to suppress, if easy - under Age Range, suppress the pull-down as these are all disease related.

I'll take it for another spin, but wanted to get these to you.

**Comment by jimmyzhen** [comment] 2016-10-31 22:18
Thanks, @selinad!

**Comment by wrightmw** [comment] 2016-10-31 23:53
@jimmyzhen Looks great. 
If a curator wants to use a population database like ExAC as their Control Cohort then there is no way for them to save the version number they used but this can be addressed in a future release. For now, could encourage the curators to put this information in the Control Cohort Label.

**Comment by selinad** [comment] 2016-11-04 07:44
Unfortunately, I can't get to this page - when I click + Case-Control on GDM, I get error:
![screen shot 2016-11-04 at 12 36 51 am](https://cloud.githubusercontent.com/assets/11320314/19998071/d69ba55e-a227-11e6-8955-9c3e3e946f35.png)

**Comment by jimmyzhen** [comment] 2016-11-04 16:27
Hi @selinad,

This might have been related to the page not yet added to the production data. It should have been addressed by Karen as we speak.

**Comment by kilodalton** [comment] 2016-11-07 23:39
Included in last release (R8). Nice job and thanks for your hard work.

**Closed by kilodalton** 2016-11-07 23:39 UTC
Labels: gene curation re-work, R8, release ready
