### ISSUE TITLE
Updating existing Variant preferred name bugs

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#617] opened 2016-02-22 21:52 UTC
When we were on the phone today we had both Erin (Windows 7) and Tasha (Mac OS) try to update their existing variants in R4.

Both were able to see their existing VariationID and pop up the modal.  The VariationID appeared in the modal, but had to be completely erased and reentered for the Retrieve button to display.

Retrieve worked correctly on the modal window, but when they hit Save, the ClinVar Preferred Title was not displayed (and when they hit Submit on the form, the same was true).

We had both check since they use different OS's.

For my test data in curation-test, it looks like my variants have already been updated.  Now I can't remember if I did that after the test version was updated (ie after R4 release).

How is it supposed to work?  We were thinking curators would manually update.

thx!
the *ights.

**Comment by kilodalton** [comment] 2016-02-25 19:32
Details:

Editing existing Clinvar ID (that does not have preferred name stored):

In Modal window: 
--Retrieve from ClinVar Button should be activated if ClinVar preferred name is not available when modal is opened (currently incorrectly inactive until user edits/re-enters number)

After User saves ID/preferred name in modal:
--Current page being edited does not display newly updated Variant info (preferred name not displayed)
--When page is saved  "clinvarVariantTitle"  is not being updated in db  for Variant

**Comment by jimmyzhen** [comment] 2016-02-28 00:25
Hi @kilodalton,

I've tried testing the "Edit ClinVar ID" button behavior in my local instance. However, I was not able to reproduce the 2 described problems in the use case above (e.g. **"After User saves ID/preferred name in modal"**).

In the curation-test instance (e.g. **curation-test.clinicalgenome.org**), except for the "111" VariantID, other tested IDs (e.g. 11, 110, 222) all resulted in the preferred name being updated on the current curation page as well as being saved upon the successful form submission.

That said, when in the modal box of the curation-test instance, clicking the "Retrieve from ClinVar" button (for the "111" input value) would actually fetch and display the preferred name string. Just clicking the "Save" button of the modal box does not update the variant info for the "111" VariantID (which I couldn't reproduce in my local instance).

Could it be something wonky about the database being used by the curation-test instance?

**Comment by kilodalton** [comment] 2016-02-28 00:37
@jimmyzhen Since it happens in both test and production it is not unique to either version of the DB. 

Let me investigate and I will create a testing scenario for you to reproduce the problem.

**Comment by jimmyzhen** [comment] 2016-03-01 07:15
@kilodalton I've implemented a fix for this and spun up an instance at:
https://617-jz-variant-preferred-name-71f5f49-jzhen.demo.clinicalgenome.org

Please give it a try and let me know whether it fixes the problem as expected. Thanks!

**Comment by kilodalton** [comment] 2016-03-04 23:14
Variations needed for testing:
- "clinvarVariantTitle" key not already present in saved data (e.g. production scenario)
- "clinvarVariantTitle": "" , i.e.  key present and value is actually  `""`
- "clinvarVariantTitle": "TEST", i.e. modal can update pre-existing (potentially outdated) title

Bugs to fix on branch in progress for this ticket:
- Editing an existing ClinVar variant id should not create a new Variant (no increase in records in URL/variants-->only update current Variant )
- Modal does not always update page for empty value situation (e.g. `""`)
- Modal does not always update page when  "clinvarVariantTitle" has a pre-existing value

**Comment by jimmyzhen** [comment] 2016-03-08 08:22
Hi @kilodalton,

1. The bugs described in your previous comment have been addressed. The changes have been committed into the existing PR.
2. I've discussed the concern with the curators in regards to the displayed curator name of each added variant in the **Associated Variants** panel. They are aware that the displayed curator name currently can just be the curator who added the variant, since we are not capturing the data on the curator who last  assessed the variant.
3. I've also asked the curators on the 2 places in which we can currently access the variant curation page from the Curation-Central page. They have determined that there shouldn't be any links in the variant titles under the **Associated Variants** panel. So I have implemented changes to address this problem, along with making the displayed note of "edit" variant curation more visible to users.

**Comment by kilodalton** [comment] 2016-03-16 02:49
Needs additional work and testing to work with production data. 

My suspicion (though I haven't looked yet) is that it does not properly handle the case where `"clinvarVariantTitle"` is not a field in the variant object at all in postgres. Based of looking at the jsonschema package previously for a different reason is that the current implementation of jsonschema we are using is actually saving the empty `key: value` pair (defaulting to saving all fields even if not used/filled out, as in saving `"clinvarVariantTitle": ""` in all our current instances based on the current code.  This would not be the situation in production because an upgrade script was not run against the existing variants when the modal+schema changes were implemented. If this is the problem, testing in dev will require manually editing of data on a running *test* local/instance directly in postgres to have a variant object that does not have the `key: value` pair  `"clinvarVariantTitle": ""` for one or more variants, then checking that the modal works on that variant.

Will need further investigation.

**Comment by kilodalton** [comment] 2016-03-16 02:52
Addendum/Note: Postgres 9.4 (our current db version) does not allow editing of individual fields of a JSON object, the JSON object must re-written as a whole. (I believe 9.6 does though).

**Comment by kilodalton** [comment] 2016-03-17 06:03
Remaining issues were fixed by doing and upgrade on any prod variant data that was missing `"clinvarVariantTitle": ""` and also back filling this value  for records that had a clinvar id but no preferred title in the db in #635/PR #636

**Comment by kilodalton** [comment] 2016-03-18 05:33
Included in last release (R5). Nice job and thanks for your hard work.

**Closed by kilodalton** 2016-03-18 05:33 UTC
Labels: bug, priority: high, R5, release ready
