### ISSUE TITLE
Incorrect dashboard history timestamp

### ISSUE THREAD

**Issue by h-tong** [ClinGen/clincoded#2082] opened 2019-11-22 19:22 UTC
After deleting a group, family, or individual from a GDM, the action shows up in the dashboard history; however, the timestamp displays the current date and time instead of when the action was actually performed.

This is due to the wrong field being used to display the date and time.

**Comment by shaungc-su** [comment] 2019-12-03 22:01
`history.last_modified` should be `history.primary.last_modified` instead. Currently, `history.last_modified` will be `undefine`. In such case, it will be equivalent to `moment(undefine)`. Seems like `moment()` will just return current datetime if the argument is undefine, this is likely the cause.

Seems like create and modified are not suffering from this issue, since their timestamp field is stored in 1st level of `history`, as `history.date_created`.

Besides group, family and individual mentioned, the case control seems to use the same pattern to show delete time and hence suffers the same issue as well:

Right after delete case control
![Screen Shot 2019-12-03 at 1 58 18 PM](https://user-images.githubusercontent.com/57968339/70093344-0982b600-15d5-11ea-8c7b-27b228c17b80.png)

After a minute and refresh:
![Screen Shot 2019-12-03 at 1 59 13 PM](https://user-images.githubusercontent.com/57968339/70093388-20290d00-15d5-11ea-8474-16f70b073fa3.png)

The delete time should be fixed as `1:58 pm`.

Will fix the timestamp in 4 places: group, family, individual and case control.

**Comment by wrightmw** [comment] 2019-12-04 05:19
@shaungc-su 
This looks correct to me. I added several permutations of G, F, and I, and in each instance when I deleted them the deletion event now showed up on the Recent History table in the dashboard with the correct deletion timestamp. I can also confirm that when I waited and refreshed my browser the deletion timestamps remained with the correct times. Thank you!

**Comment by cgpreston** [comment] 2019-12-04 18:41
I also tested this and it looks right to me as well, in each instance (family, group and two individuals) I deleted the evidence, saw the event appear on the Recent History tab, refreshed the page,  signed in and out and the timestamps remained correct. Thanks @shaungc-su !

**Comment by cgpreston** [comment] 2019-12-17 22:02
Confirmed expected behavior on R30 test candidate, thanks @shaungc-su!

**Comment by wrightmw** [comment] 2019-12-17 23:53
Looks good to me. Thanks @shaungc-su

**Comment by wrightmw** [comment] 2020-01-10 17:20
Added as part of Release 30 (R30)

**Closed by wrightmw** 2020-01-10 17:20 UTC
Labels: GCI, bug
