### ISSUE TITLE
Fix Phenotype requirement on Model Systems entry

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#533] opened 2016-01-14 00:04 UTC
In below image, If I enter free text, shouldn't require HPO for Human phenotype
<img width="975" alt="screen shot 2016-01-13 at 2 22 40 pm" src="https://cloud.githubusercontent.com/assets/11320314/12311876/28d71788-ba0f-11e5-95d6-f113ff8152fe.png">

**Comment by mrmin123** [comment] 2016-01-21 22:06
@selinad I couldn't reproduce this on the latest dev build:

![image](https://cloud.githubusercontent.com/assets/4326866/12496041/084e9880-c048-11e5-825d-8d7ccd938b46.png)

Could you re-check, and show me/provide me any console messages if the error persists?

**Comment by jimmyzhen** [comment] 2016-02-03 19:47
Hi @selinad,

Per discussion in the meeting, the reported bug has been addressed in recent changes committed to the `dev` branch. And thus we just need to spin up an EC2 instance with the latest version of the `dev` branch for the curators to verify the bug fix.

So below is the EC2 instance URL for your review:
https://533-jz-dev-9222ca0-jzhen.demo.clinicalgenome.org/

Please let us know if there are any questions. Thank you.

**Comment by wrightmw** [comment] 2016-02-03 20:36
@jimmyzhen On that instance the Edit Family page still says to input HP_ IDs, see below
![hp_000000](https://cloud.githubusercontent.com/assets/15131169/12796263/bea49678-ca72-11e5-8161-d0eacb243705.png)
:

**Comment by selinad** [comment] 2016-02-03 20:39
I think maybe these 2 issues have become confusing because they are both HPO related - @jimmyzhen, this is for the bug fix, correct, and does not include the issue dealing with text changes for "HP_" vs. "HP:"?

**Comment by jimmyzhen** [comment] 2016-02-03 20:44
@wrightmw, @selinad, this issue has nothing to do with the text changes for "HP_" requested in #562. In fact, I have not started working on it yet ;)

**Comment by wrightmw** [comment] 2016-02-03 20:47
@jimmyzhen No worries… it was just me getting confused :simple_smile:

**Comment by jimmyzhen** [comment] 2016-02-04 02:17
@wrightmw, @selinad,

The originally described symptom in this issue appears to have been resolved in the current version of the `dev` branch. Can you verified whether that is the case (e.g. https://562-568-569-jz-text-change-a125269-jzhen.demo.clinicalgenome.org)? If so, we may be able to just close this issue. Thanks!

**Comment by selinad** [comment] 2016-02-04 02:41
The bug is gone!  Was there actually one or was it just me since it didn't seem to be reproducible?

thx @jimmyzhen !

**Comment by jimmyzhen** [comment] 2016-02-04 17:39
@selinad It was possible that a bug did actually exist at the time you reported it. But when Min looked into it 8 days later, it had been potentially resolved by other fixes.

**Comment by selinad** [comment] 2016-02-04 18:15
Got it - thanks, @jimmyzhen .  Glad all works well.

**Comment by jimmyzhen** [comment] 2016-02-04 19:16
Great. Then I am closing this issue since there is no development work required.

**Closed by jimmyzhen** 2016-02-04 19:16 UTC
Labels: bug, curator review, priority: high, R4
