### ISSUE TITLE
Update to React 0.14

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#288] opened 2015-09-11 18:17 UTC
React 0.14 has some [breaking changes](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html) from React 0.13 that we use now.

**Comment by kilodalton** [comment] 2015-09-12 20:13
Note: React  0.14  is still in release candidate stage (Sept 2015). We will evaluate implementation schedule after  0.14 is no longer in RC status.

**Comment by forresttanaka** [comment] 2015-10-22 18:53
Because our ENCODE roots uses a deprecated React function in many critical places (```setProps```), I don’t see completing this any time soon. Targeting R3 for now.

**Comment by forresttanaka** [comment] 2015-11-05 20:00
Status update: Removed all uses of setProps and mostly replaced with setState on new App state properties, either directly or in the HistoryAndTriggers mixin. It now builds and runs, and delivers no errors so far.

Also removed refs.var.getDOMNode() references because refs.var now delivers the DOM node object itself in 0.14.

Next steps are to use the new stateless component mechanism to clean up the Family, Group, and Individual pages which currently use regular functions, and we have to pass _this_ to allow them to share properties with the parent component. We can replace those functions with stateless components with properties they need passed in.

**Comment by forresttanaka** [comment] 2016-01-04 16:21
Instance that’s up to date with dev: https://288-ft-react-14-68f226d-fytanaka.demo.clinicalgenome.org

**Comment by selinad** [comment] 2016-01-05 19:08
Hi @forresttanaka 

When I check the checkbox (below) on the experimental, the boxes below should become white and are not (everything else good so far)

![screen shot 2016-01-05 at 11 06 48 am](https://cloud.githubusercontent.com/assets/11320314/12124834/94685256-b39c-11e5-9de9-601552257b20.png)

**Comment by selinad** [comment] 2016-01-05 19:11
Same thing happens on Biochemical Function A page:
![screen shot 2016-01-05 at 11 10 24 am](https://cloud.githubusercontent.com/assets/11320314/12124902/fc709b7e-b39c-11e5-8bd8-70aea69ba11a.png)

**Comment by selinad** [comment] 2016-01-05 19:12
@mrmin123 - before, if I switched from A to B under Biochemical Function, wouldn't it clear all of A entries I had made so far (within the page)?  Could be holiday rust...

**Comment by selinad** [comment] 2016-01-05 19:16
Did the assessment pull-down use to default to the previously selected value? (I think not, but checking) - we may want it to do this if possible...

![screen shot 2016-01-05 at 11 14 52 am](https://cloud.githubusercontent.com/assets/11320314/12125015/afcdc336-b39d-11e5-8185-c6409925fcb6.png)

**Comment by mrmin123** [comment] 2016-01-05 19:27
@selinad Previously, switching from A to B did not clear the fields... Switching from Biochemical Function to another Experimental Data Type would, however.

**Comment by selinad** [comment] 2016-01-05 19:29
Thanks, @mrmin123.  @wrightmw - let me know if you think switching should clear fields

**Comment by selinad** [comment] 2016-01-05 19:38
I've run through most everything - the only problem I encountered while logged in was the check boxes.  Did not see any weird delays, etc.

However, I logged out and logged in again and it does not show my record under "Your GDMs" - I can see it if I go to all and get to it from there....

@forresttanaka I wonder if this is related to the fact my name is missing in the "Welcome, !" line...?

**Comment by wrightmw** [comment] 2016-01-06 18:16
I haven't encountered any other problems. Likewise when I logged out and back in again it does not show my record under "Your GDMs" and that my name was missing from the "Welcome, !".

**Comment by wrightmw** [comment] 2016-01-06 18:19
@mrmin123 @selinad I would say switching from A to B should not clear the fields but switching from Biochemical Function to another Experimental Data Type should.

**Comment by kilodalton** [comment] 2016-01-06 22:09
@selinad or @wrightmw Please make a separate ticket for the switch A/B->clear scenario as that is different non-previously-implemented functionality unrelated to the React upgrade.

**Comment by kilodalton** [comment] 2016-01-06 22:15
@forresttanaka Please check #524  (Replace deprecated react-tools and jstransform with babel) to see if it can be include with this upgrade.

**Comment by wrightmw** [comment] 2016-01-07 01:06
I agree with @selinad as illustrated above. It would be better if the experimental data assessment defaulted to the value that had been selected previously.

**Comment by wrightmw** [comment] 2016-01-07 19:20
Ticket created for switching between A and B for Biochemical function: #527

**Comment by forresttanaka** [comment] 2016-01-11 17:48
New instance: https://288-ft-react-14-05bced1-fytanaka.demo.clinicalgenome.org

Fixes the checkboxes not enabling the text areas, and the default value of the assessment menu. I haven’t yet done the babel conversion. If I don’t get to that tomorrow, that might need to wait for the end of the week.

**Comment by forresttanaka** [comment] 2016-01-11 17:51
Incidentally, buildout (really npm install) loads up React 0.14.6 right now, so it’s keeping up with React’s updates. We don’t use npm-shrinkwrap right now (a mechanism to lock versions of packages npm installs; ENCODE has used that forever).

**Comment by mrmin123** [comment] 2016-01-11 19:04
@forresttanaka Did a brief test and the checkboxes and assessment menu works as intended, thanks.

**Comment by forresttanaka** [comment] 2016-01-14 21:04
Spun up a new instance with this branch brought up to date with dev.

I do see a minor bug that I think would be a good one for @jimmyzhen to work on: The default value of the assessment menu when viewing a variant is set to Not Assessed. Likely the same problem with Experimental Data default assessment value that @selinad and @wrightmw found with the previous build.

https://288-ft-react-14-ef2532d-fytanaka.demo.clinicalgenome.org

**Comment by jimmyzhen** [comment] 2016-01-14 23:25
@forresttanaka What is the expected default value of the assessment menu when viewing a variant?

**Comment by jimmyzhen** [comment] 2016-01-28 19:55
I made a new branch off Forrest's 288-ft-react-14-68f226d-fytanaka and merged the "dev" branch into it. The purpose is for us all to test the entire site in regards to the ReactJS 0.14 upgrade.

The EC2 instance for this new branch is now accessible at:
https://288-jz-react-14-dev-merged-d2d4581-jzhen.demo.clinicalgenome.org

Please test the functionality on the entire site to ensure the expected behaviors continuing to work as expected given the combination of ReactJS 0.14 upgrade and the latest merged changes in the "dev branch. Thank you.

**Comment by forresttanaka** [comment] 2016-01-28 19:58
Testing should include that everything works properly when you log in and log out — most of the changes that I felt very vague about their effects have to do with that. The other widespread change has to do with getting form values — the 0.14 method changed, and it’s an easy change. But it did affect code kind of all over. Look to see that what you entered on forms is the value that ends up in the objects — generally the View pages and editing objects should expose any problems here.

A past problem that caused the checkbox failure in Experimental Data had to do with mutating the React props inside a component. That was never proper in React but you could get away with it before 0.14. But React 0.14 throws a JS error if you try to do that. I’m pretty sure only the Experimental Data module did that, so I doubt that’s anything to check for generally.

**Comment by selinad** [comment] 2016-01-29 01:23
I could swear that my first attempt at login showed the GDM and I was logged out right away.  Had to login again - then it worked.  Tried logging out and logging in with my other accounts and all worked fine.  There is a little bit of a back and forth thing going on (looks like it starts, goes backwards, and recovers) - could be due to the instance?

**Comment by jimmyzhen** [comment] 2016-01-29 01:38
@selinad I just tried to sign into the EC2 instance in both **IE11** and **Chrome** in _Win7_, but I was not able to reproduce the behavior you experienced. I will check with others tomorrow to confirm the issue. _Thank you._

**Comment by selinad** [comment] 2016-01-29 01:59
Hi @jimmyzhen - thanks!  Just tried on Safari and Firefox with no issues.

Also, have tried pretty much everything and all looks great!  No problems with checkboxes as before. 

Thank you and Nice work!!!

**Comment by jimmyzhen** [comment] 2016-01-29 02:07
@selinad Glad to hear! And thank you for taking the time to test the site's functionality in various browsers!

**Comment by wrightmw** [comment] 2016-01-29 20:03
@jimmyzhen Apart from the odd error message when logging in using Firefox, it all looks like it's working well in multiple browsers. Great work!

**Comment by jimmyzhen** [comment] 2016-01-29 21:12
Thanks, @wrightmw!

The odd "network request failed" message in Firefox appears to be a known issue, and it can be reproduced in the current ClinGen production site as well as ENCODE's production site. So it is not related to the changes involved in this ticket.

**Comment by kilodalton** [comment] 2016-02-08 19:13
Moving ticket status, to separate it from other tickets going in to R4. Will be re-reviewed after the current release and current dev is merged in.

**Comment by jimmyzhen** [comment] 2016-02-17 19:46
@selinad, @wrightmw,

In regards to this ReactJS v0.14 upgrade, I have added a few more fixes to this ticket to address various issues. Furthermore, this upgrade has included all the R4 changes. The EC2 instance for this ticket is now accessible at:
https://288-jz-react-14-dev-merged-7f9ab88-jzhen.demo.clinicalgenome.org

Please test the functionality on the entire site to ensure the expected behaviors continuing to work as expected given the combination of ReactJS 0.14 upgrade and the latest changes from R4.

It will be great if you can look into this in these couple of days so that @mrmin123 may still have time to review/merge the PR (if all goes well) prior to his vacation.

**Below are comments from Forrest (copied from above) in regards to testing:**
"Testing should include that everything works properly when you log in and log out — most of the changes that I felt very vague about their effects have to do with that. The other widespread change has to do with getting form values — the 0.14 method changed, and it’s an easy change. But it did affect code kind of all over. Look to see that what you entered on forms is the value that ends up in the objects — generally the View pages and editing objects should expose any problems here.

A past problem that caused the checkbox failure in Experimental Data had to do with mutating the React props inside a component. That was never proper in React but you could get away with it before 0.14. But React 0.14 throws a JS error if you try to do that. I’m pretty sure only the Experimental Data module did that, so I doubt that’s anything to check for generally."

Thank you!

**Comment by jimmyzhen** [comment] 2016-02-19 18:37
Hi @selinad, @wrightmw,

Please use the following new React 14 instance for testing/review:
https://288-jz-react-14-dev-merged-e0ef69d-jzhen.demo.clinicalgenome.org

Thank you.

**Comment by selinad** [comment] 2016-03-16 23:33
I have to say, this is looking really good!  I haven't found anything unusual.

I did notice one thing - should probably make a separate ticket (let me know):

![screen shot 2016-03-16 at 4 31 40 pm](https://cloud.githubusercontent.com/assets/11320314/13831949/be6f8d64-eb94-11e5-8d2f-86438fe33661.png)

I was looking in Tasha's record - long labels do not wrap on the palette - probably not react 0.14?  I guess I don't test with long labels!

**Comment by jimmyzhen** [comment] 2016-03-16 23:40
Hi @selinad,

It should be a simple CSS fix and it is not related to react 0.14 upgrade. A new ticket will be greatly appreciated.

**Comment by selinad** [comment] 2016-03-17 00:10
thx @jimmyzhen!

**Comment by wrightmw** [comment] 2016-03-17 00:14
Looks good to me

**Comment by kilodalton** [comment] 2016-03-18 05:36
Included in last release (R5). Nice job and thanks for your hard work.

**Closed by kilodalton** 2016-03-18 05:36 UTC
Labels: enhancement, R5, release ready
