### ISSUE TITLE
GCI Expert Review and Approval - Readiness to publish

### ISSUE THREAD

**Issue by jimmyzhen** [ClinGen/clincoded#1420] opened 2017-07-14 19:07 UTC
Specs for publishing data to clinicalgenome.org:
1) Prerequisite
Only approved data can be published.
2) Permissions
User must be acting on behalf of (logged in as) an affiliation and the affiliation must have the right to publish data ("publish_approval" field in affiliation JSON).
3) UI
a) User will be presented with a "Publish" panel similar to the provisional and approved panels.  There will be a form field to add comments, but not to apply a date (the published date will be generated and stored automatically).  Once the data has been published (more specifically, the message has been successfully received by the Data Exchange server), a "Published" label will be added (again, similar to the provisional and approved states of the data).
b) At present, the plan is to allow users to unpublish (mark as invalid or possibly remove) data that has been published to clinicalgenome.org.  For any published data, the user will have the option to unpublish it (via a button).  Once the data has been unpublished (message received by the Data Exchange server), an "Unpublished" label will be added.

**Comment by jimmyzhen** [comment] 2018-04-17 20:54
@bryanwulf, the original description in this ticket could be potentially out-of-date. So please feel free to update it as you see fit.

The bottomline is that this ticket will serve as the place for you, @selinad, and @wrightmw to define/iterate the specs on how the UI should be and what the expected behaviors are for the users to publish classification data to the Data Exchange.

**Comment by wrightmw** [comment] 2018-05-24 19:45
@bryanwulf 
I'll look at the data submission in more detail later (currently at conference), but I just wanted to quickly note a few points:
1) I don't think the "Date published" field should be auto-filled until the curator goes through to the preview... it could be similar format to the "Entered by" field...e.g. greyed out text  that says something like "Date published will be entered upon publication"...

<img width="1157" alt="screen shot 2018-05-24 at 12 30 38 pm" src="https://user-images.githubusercontent.com/15131169/40509775-6b003c88-5f4f-11e8-9120-a76b18831115.png">

... and then gets auto-filled on the preview panel:

<img width="1155" alt="screen shot 2018-05-24 at 12 31 05 pm" src="https://user-images.githubusercontent.com/15131169/40509859-a1122822-5f4f-11e8-83b2-fb38feff7f07.png">

2) There needs to be a "Date published" in the saved Approved Classification. I love the purple (fuschia?) "PUBLISHED" icon but I find it confusing after the Approved icon.
Personally, I would prefer a separate line that says "Date published" and then the purple "PUBLISHED" icon would appear after the date on that line.
<img width="1152" alt="screen shot 2018-05-24 at 12 31 24 pm" src="https://user-images.githubusercontent.com/15131169/40510021-3510312c-5f50-11e8-9d96-ccbe08b2efad.png">

@selinad will also weigh in on this :-)

Also, FYI in your instance I cannot score Case Control evidence.

**Comment by wrightmw** [comment] 2018-05-25 01:30
@selinad I think we also want the "PUBLISHED" icon to also appear in the header?

Also, @bryanwulf where will the "Additional Comments" that someone adds to the "Publish Classification" panel be shown?

**Comment by selinad** [comment] 2018-05-25 05:05
@bryanwulf so fun to see all of this coming together!  Your UI looks great!

I agree with @wrightmw 's comments -- although I don't mind the date filled in as the date of publication will be the same date as when one publishes (as apposed to Provisional or Approved).  In fact, I'd argue for keeping it so it's clear that is what it will be when button hit (unless spanning midnight!).

Agree about having new line for date published, with fushia tag on that line, and having publication comments show.  Problem is that this could get long.  We should think harder about this tomorrow.

Would be nice to have link to website on published section

I think we need to remove Published from older one as they are not both published -- is this working for updates to the website (meaning new publications for same Classification being replaced?)  

![image](https://user-images.githubusercontent.com/11320314/40526888-3ef64d54-5f9e-11e8-9169-f119588fbeeb.png)

Thank you for your hard work on this -- huge step!

**Comment by bryanwulf** [comment] 2018-05-25 08:18
I've updated the instance to display publication data in the panel:

![image](https://user-images.githubusercontent.com/32915557/40533995-5c1f34e8-5fb9-11e8-8af5-2898f40ae40c.png)

**Comment by selinad** [comment] 2018-05-25 14:10
HI @bryanwulf one other thing before I forget  -- could we please add "PUBLISHED" to Dashboard"

![image](https://user-images.githubusercontent.com/11320314/40548827-a999566e-5fea-11e8-85a8-ef98b2a38c0e.png)

Also, in the header?

![image](https://user-images.githubusercontent.com/11320314/40548855-bdd7b6de-5fea-11e8-82a9-71cd2bcfae93.png)

**Comment by selinad** [comment] 2018-05-25 14:15
@bryanwulf Looks great!

A few things, if reasonable:
- Could the light gray line go all the way across?
- Could the View Approved Summary then be moved up above that light gray line?
- Then add a link to the website entry below the gray line?

Not certain whether you have error messages, etc. that we can test yet....


![image](https://user-images.githubusercontent.com/11320314/40548941-fdfa8660-5fea-11e8-9ab1-e370c7175c28.png)

**Comment by selinad** [comment] 2018-05-25 22:42
Additional items:
- for a failure back notice, have error string "Request failed; please try again in a few minutes or contact helpdesk: clingen-helpdesk@lists.stanford.edu"
- for a a new published on top of an existing, remove PUBLISHED status for previous one, but keep published 
- Add new line to header and include Date Published: timestamp and then PUBLISHED tag next to it
- Add new line to Evidence Summary and include Date Published: timestamp and then PUBLISHED tag next to it
- Add new line to Dashboard and include and include Date Published: timestamp and then PUBLISHED tag next to it
- Add "Unpublish" button similar to the gold one that appears for Approve and when click opens up panel above (after page refresh) that gives you place to add Additional Comments and Preview, then need Submit. Then change "Published by" to "Unpublished by" and say "Date unpublished" and have unpublished comments override last Additional comments.
- make date published on panel be consistent with other panels (appears on save)
- gray line goes all the way across
- above gray line is View Approved and Unpublish button described above
- Have link to clinicalgenome.org and underneath say "The Approved Classification may take 5-10 minutes to appear on the website" (we can provide a search string in a later release)
- potential icon?

**Comment by selinad** [comment] 2018-06-10 20:00
@bryanwulf -- in process of testing instance.

If not for this release, for another release, if not consuming, it would be nice to put Affiliation name in light gray here (as for other fields):

![image](https://user-images.githubusercontent.com/11320314/41205736-f90e3c08-6cad-11e8-9df4-5aa489d0b9de.png)

The publish button is not doing anything when I click on it -- here is the dev tools (let me know if you need something different):

![image](https://user-images.githubusercontent.com/11320314/41205751-46f4bb5e-6cae-11e8-8fb2-255663ddd96d.png)

**Comment by selinad** [comment] 2018-06-10 20:04
This looks great @bryanwulf 
![image](https://user-images.githubusercontent.com/11320314/41205776-ca21ace4-6cae-11e8-910a-fa0dcab2d1e5.png)

**Comment by selinad** [comment] 2018-06-10 20:13
Hmmm...

When I went back to the above Classification I saw the magenta Publish Summary button -- when I did that, the Affiliation was filled in:
![image](https://user-images.githubusercontent.com/11320314/41205793-04aff1ae-6caf-11e8-9ffd-18d677d12037.png)

and the Publish was successful!  I don't know if that gives a clue as to why I couldn't do it before...this was a new record created since the last update of the instance.

![image](https://user-images.githubusercontent.com/11320314/41205807-27b23428-6caf-11e8-8b7c-77c861a4c445.png)

@bryanwulf great that you have the link there!  I can't see it on the site yet either through the link or searching the dev website, but am waiting...

**Comment by wrightmw** [comment] 2018-06-11 18:20
@bryanwulf 
The "Unpublish Classification" is current incorrectly entitled ""Publish Classification""

**Comment by wrightmw** [comment] 2018-06-11 18:52
@bryanwulf 
I went into the demo instance that has prod data. I went into an Approved entry and Saved my own Provisional and Approved Classification based on the existing data. When I went to publish my Approved, the Publication data appear below the old Approved Classification, rather than under my new Approved Classification:
![screen shot 2018-06-11 at 11 49 03 am](https://user-images.githubusercontent.com/15131169/41251130-d726a466-6d6d-11e8-9aff-6400d6614847.png)

**Comment by selinad** [comment] 2018-06-13 21:15
@bryanwulf I like the new Unpublish button!

After selecting Unpublish, one expectation is it is "automagically" unpublished and there are no other steps -- is there something we could do to make it more obvious they still have to unpublish?  I think part of this is because the way one publishes is different -- ie. submit Publish and it goes.  In this case, pushing unpublish takes them to another step.

Could the Unpublish button pop up a window instead?  Not certain how intensive this would be.  It would pop up a window and offer chance to explain, then they would Unpublish.

Another thought -- the button doesn't say "Unpublish Summary" -- instead it says something that lets user know they will get the unpublish modal or instead is a link that says that.  This is complicated by fact the Unpublish is so far above where they originally clicked the button.  Open to ideas....let me know your thoughts.

![image](https://user-images.githubusercontent.com/11320314/41378018-ac91d6d4-6f12-11e8-9c99-620f00a66933.png)

**Comment by selinad** [comment] 2018-06-13 21:18
@bryanwulf unless we are going to provide links for the disease as well, I don't believe we need this link here for mode of inheritance:

![image](https://user-images.githubusercontent.com/11320314/41378658-95bfdbd4-6f14-11e8-8376-57dd972c622e.png)

**Comment by selinad** [comment] 2018-06-13 21:37
@bryanwulf now in the instance with prod data and trying to publish an existing prod record that was in progress -- after hitting Publish, get this (looks like nothing happens):

![image](https://user-images.githubusercontent.com/11320314/41379590-3d11d692-6f17-11e8-8b9f-6511879e2973.png)

![image](https://user-images.githubusercontent.com/11320314/41379623-4cfde28a-6f17-11e8-84b3-5f709519cf9a.png)

**Comment by bryanwulf** [comment] 2018-06-13 21:52
@selinad Some of the issues you're encountering may be the result of "in progress" changes.  I'm actively working on the problem reported by Matt earlier this week and it's only reproducible on the instance with production data.  I haven't added the aforementioned changes to the instance with test data, so I would recommend doing any additional testing there (until I can give an "all clear" on the instance with production data).

**Comment by bryanwulf** [comment] 2018-06-14 15:09
@wrightmw @selinad All instances have been updated with a fix for the problem identified by Matt (publishing the wrong classification).  I expect the problems identified by Selina over the past 24 hours (out-of-sync buttons and non-functional publish) should be resolved as well.

**Comment by selinad** [comment] 2018-06-14 16:33
HI @bryanwulf 

In prod version and working to publish a prod classification that was in progress:
- publication notes in correct place!
- will you be adding Published tag to the header? 
![image](https://user-images.githubusercontent.com/11320314/41425451-9edbe3c4-6fb5-11e8-9292-965a234de454.png)

- the Unpublish does nothing right now (not sure if that has to w/fact can't even get to dev website at moment
![image](https://user-images.githubusercontent.com/11320314/41425484-c23dfe92-6fb5-11e8-93b3-6a9695d981f3.png)

- will you be adding Published to Dashboard?
![image](https://user-images.githubusercontent.com/11320314/41425553-ee71207a-6fb5-11e8-94d1-2828989b777a.png)

**Comment by wrightmw** [comment] 2018-06-14 16:49
@bryanwulf "Unpublish" works if I go back to an entry that I previously published, but Unpublish does nothing if I stay on the same page after publishing and decide to Unpublish it.

**Comment by wrightmw** [comment] 2018-06-14 16:52
@selinad 
Once someone has Unpublished a Classification, should we provide them with the option to Re-publish or should we take away the publish button?
![screen shot 2018-06-14 at 9 51 16 am](https://user-images.githubusercontent.com/15131169/41426501-b22ac2c6-6fb8-11e8-8d1e-1c22adbb8c66.png)

**Comment by wrightmw** [comment] 2018-06-14 16:54
@selinad I think the "unpublished" tag should be the same colors as the Unpublished button (white with 'fuschia' text). Currently at first glance this looks no different visually from published. Do you agree?

**Comment by wrightmw** [comment] 2018-06-14 16:56
@selinad Do you think we should also add the "published" tag to the Evidence Summary?

**Comment by wrightmw** [comment] 2018-06-14 17:11
@bryanwulf I've tested several times and I cannot repeat the old error (where the published info was associating with with archived classification instead of the current one)...which is great! Bug squashed!

**Comment by selinad** [comment] 2018-06-14 17:18
@wrightmw I don't think we need it in the Evidence Summary -- one can only get there from Approved and it says published next to it.  At least for this time or if someone asks for it.  As I remember, it might be tricky.

**Comment by selinad** [comment] 2018-06-14 17:20
@wrightmw I do agree it would be nice to have the Unpublished tag be like the unpublish button.

I couldn't get mine to Publish....what type of classification did you use (i.e. production record, one that was previously started or a new one?)

**Comment by wrightmw** [comment] 2018-06-14 17:33
@selinad Whether I can unpublish or not does not seem to be dependent on the type of classification but more due to different workflows. After publishing a Classification, if I migrate away from the Classification page and then come back again... then I can unpublish it. But if after publishing a Classification, I stay on that page then I can't unpublish it.

**Comment by bryanwulf** [comment] 2018-06-14 17:53
Regarding attempts to publish/unpublish immediately after completing the opposite process (e.g. hitting the "Unpublish Summary" button as soon as it appears after publishing), Matt is on the right track (leaving the page and returning alleviates the problem).  I'm working on a solution to allow the desired/expected behavior (to not require leaving the page).

Also, adding publish/unpublish status away from the classification history panel (header, dashboard, etc.) is still in progress.

**Comment by bryanwulf** [comment] 2018-06-15 22:31
@wrightmw @selinad I've updated the instances with a few changes:
1. Fixed the "can't unpublish immediately after publishing" problem (described in previous comment).
2. Added published status to header (only place so far).
3. Modified the heading color of the publish and unpublish panels (per discussion with Selina).

Here's what the error message looks like (if needed, I can demonstrate its appearance on my local instance):
![image](https://user-images.githubusercontent.com/32915557/41491877-81ba9a32-70b0-11e8-9fa9-1b3ed36b804f.png)

**Comment by wrightmw** [comment] 2018-06-15 22:54
@bryanwulf Still testing...looking good so far:
1. This issue is fixed now
2. It's there... great!
3. The headers for Prov/Approved could be the same orange as the headers in the VCI

**Comment by selinad** [comment] 2018-06-15 23:48
@bryanwulf this is looking great!  I agree, the issue is fixed and the colors on the header are great -- thank you!

Here's one issue we need to address -- when there is an already published Approve and then a new approve, this is what shows:

![image](https://user-images.githubusercontent.com/11320314/41493371-5840e6d8-70bb-11e8-8d59-1c66c39a1703.png)

This is misleading as the new Approved one is note published (ugh). What should we do here?  One thing might be to put a warning that this Approved reflects an Approved after the data of the last approved's publication?  (up in the header) "This Approved not yet published; an earlier Approved Classification is published).  Maybe the "!" icon with a roll over text?

**Comment by selinad** [comment] 2018-06-18 17:22
@bryanwulf I know you've asked about this a couple of times

![image](https://user-images.githubusercontent.com/11320314/41551650-54062894-72e1-11e8-8c71-e16fb807f3ab.png)

My thoughts:
- leave as is and remove the "..."
- or, do that plus make this a fuchsia colored box (like the scroll over color for the unpublish button)

**Comment by selinad** [comment] 2018-06-18 17:50
@bryanwulf this ticket is looking really good!  The New Provisional tag is working well.  Here are release thoughts:

This release:
- add Published tag to dashboard
- add icon with explanation (next to Published)
- fix the box where "..." is present (maybe make it fuchsia, too)
- can you take out link to HPO for mode of inheritance?

Next release
- come up with way to distinguish from purposeful unpublish and overwritten published

Please feel free to adjust @bryanwulf , @wrightmw

**Comment by wrightmw** [comment] 2018-06-18 17:56
@selinad One thing that needs to be added this release is the differential between prod and demo. Currently, if someone published from demo it would go to the website.
Of those items you have list for "This release" do you consider all 4 to be essential showstoppers (whereby the release cannot go ahead without them), or do you think any of them could be done in next release?

**Comment by selinad** [comment] 2018-06-19 23:34
@bryanwulf -- I noticed this link "[View Current Approved]" does not work in the instance, but it does work in demo:

![image](https://user-images.githubusercontent.com/11320314/41629473-8762316c-73de-11e8-9b30-eb402fa15f1b.png)

**Comment by selinad** [comment] 2018-06-21 14:42
@bryanwulf your latest changes look great after a fair amount of testing!  I haven't encountered any bugs, etc.  The Dashboard and header all behave appropriately and publications are working!  Love the warning sign and the message with it.  I've tried many different workflows.  Nicely done!!!

**Comment by wrightmw** [comment] 2018-06-21 15:19
@bryanwulf I can concur with everything @selinad said above. The dashboard/header implementation looks great and works perfectly!

**Comment by selinad** [comment] 2018-06-21 21:10
@bryanwulf based on our meeting today, please add the curator request to always include a score (even zero) for the "totals" fields (total of 6 fields)

**Comment by selinad** [comment] 2018-06-23 17:49
@bryanwulf just getting started with full testing of this ticket, but noticed this:

![image](https://user-images.githubusercontent.com/11320314/41812176-0c97a866-76d3-11e8-916a-0b832b571a0e.png)

(see mode of inheritance field)

Should I make new ticket?  Not urgent for this release, but if "quick" you could include

**Comment by selinad** [comment] 2018-06-23 17:51
Thinking through the Unknown a bit more -- the error only appears on website side upon publish.  @wrightmw we probably need to reword the letter.  

What kind of downstream problems will this create if someone does publish?

**Comment by selinad** [comment] 2018-06-23 18:48
Hi @bryanwulf everything I've tried (all different workflows) has worked perfectly!  Header and Dashboards and sections that show status on the Classification matrix page all look great!  Only question is the one above about downstream issues for publishing on a non-hpo mode of inheritance.  Will pound a bit more, but looking great!!  Thanks for making this happen!!!!

**Comment by wrightmw** [comment] 2018-06-23 19:59
@selinad The MOI field rendering incorrectly is a behavior previously identified in the VCI, see #1616 ... so I will update that ticket to include GCI also.

**Comment by wrightmw** [comment] 2018-06-23 21:09
@bryanwulf Overall workflow for publishing and unpublishing looks great! Also, header and dashboard are rendering correctly for each circumstance. Brilliant!

**Closed** 2018-07-03 22:34 UTC
Labels: R20, gene curation interface, release ready

**Comment by selinad** [comment] 2018-07-03 22:37
Thank you for all of your hard work on this @bryanwulf -- it is a highly valued feature!  Nice job!
