### ISSUE TITLE
Secondary approvers and contributors in the GCI

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#1796] opened 2018-10-05 20:06 UTC
The Biocuration cores (and possible other curation EPs) will need the ability to have a secondary expert panel list for approval of curations, as the cores themselves do not have a broad list of expert for approval, and many of the curations will be sent to other EPs for approval. Recognition for the curation affiliation and approval EP affiliation should translate to the website.

Specifications:
(1) Under Approve classification, provide a "Secondary Approver" dropdown list. 
This list should include all current Affiliations.
Potentially add a "Secondary Approver comments section in which the name(s) of the experts for that affiliation can be logged.
[Secondary Affiliation approval v2.pdf](https://github.com/ClinGen/clincoded/files/2452110/Secondary.Affiliation.approval.v2.pdf)

(2) We would also like this "dual" credit to be recognized on clinical genome.org gene-disease validity classifications 
(2a) Addition of an area in the classification matrix under "calculated classification" that says curation performed by the following Affiliation: list per the primary approver dropdown
(2b) Under the "expert curation (date): Provide the Classification (approved date) and the following text: This gene-disease validity classification was approved by the "name of secondary approver affiliation."
[Website dual recognition.pdf](https://github.com/ClinGen/clincoded/files/2452095/Website.dual.recognition.pdf)

If these needs more specification, please advise
@wrightmw 
@jimmyzhen 
@jennygoldstein
@erinriggs
@marinadistefano
@sgoehringer

**Comment by wrightmw** [comment] 2018-10-05 20:58
@courtneythaxton Do you mean "Secondary Affiliation" instead of Secondary Approver"? Will this be a means for curators to note that another "Affiliation" was part of the Approval process?

**Comment by wrightmw** [comment] 2018-10-05 21:01
@courtneythaxton so for the dual credit on the website... would you want it to say "Affiliation X (in collaboration with Affiliation Y", or "Affiliation X AND Affiliation Y", or something else?

**Comment by courtneythaxton** [comment] 2018-10-08 20:11
> @courtneythaxton so for the dual credit on the website... would you want it to say "Affiliation X (in collaboration with Affiliation Y", or "Affiliation X AND Affiliation Y", or something else?

I believe we would want it as simple as possible. Affiliation X and Affiliation Y contributed to this gene-disease clinical validity classification. We can use the notes sections to provide more detailed information as to the exact relationship. This section may need to be included on the Evidence Summary for transparency.

@wrightmw 
@marinadistefano
@erinriggs
@jennygoldstein

**Comment by sgoehringer** [comment] 2018-10-08 20:34
It will require some work on the website site. Currently the data shared between the two systems assumed one affiliate but we can update that to handle multiple and then then we need to allow the curation to be associated with more than one affiliate in the database.  Both of those items are rather straight forward on our side.  

We should carefully consider is if we do or don't need to set a 'primary' affiliate as the producer of the curation because it won't be fun to reverse course down the line.  I can think of two display items related to the website to consider;
(1) A side effect of having everyone be an equal collaborator is when we start listing the total curations  EP have done it will cause some curations will be counted by both groups. So if someone goes to the website they may see 1000 curations completed but on the EP page it may look like 1050 were done.  (Assuming 50 were shared).  This many not be a concern but I want to mention it. 
(2) We should also consider how we want to display the affiliation order on the curation details page.  Do we simply list them alphabetically if we don't choose a primary curator?  Again, just mentioning to help work through the scenarios.

I can't speak to what is needed on the GCI side and I'll let @wrightmw @bryanwulf @jimmyzhen chime in for that.

**Comment by courtneythaxton** [comment] 2018-10-10 01:42
Hi @sgoehringer  Thank. you for the heads up on some consideration for this change and how it might affect the website. I think we (the Gene Curation Small group) have decided to talk over this some more with the Gene Curation Working Group and PIs to get some specifications. We will be sure to bring up these issues as part of the discussion.

For (1) I understand that there may be overlap and this might not be a huge concern, but notable to discuss. 

For (2) This will also be good to discuss. So far we can think of two main scenarios for the use of a secondary approver/ affiliation/ contributor. The first is when a Biocuration core has performed the curation, and the expert approval goes to one of the already established ClinGen EPs for final approval, as the cores do not have experts associated with them. The second example is when two (or possibly more) ClinGen EPs work together to contribute to a curation and classification, for example with syndromic genes. 

For the biocuration core example, I think it would be nice to distinguish the group that curated the information, versus the group that gave the final approval. 

For the second example, since both affiliations maybe contributing to the curation and approving, this would be good to distinguish. 

Any thoughts on this @mattwright @jimmyzhen @bryanwulf 
@erinriggs @marinadistefano @jennygoldstein

**Comment by courtneythaxton** [comment] 2018-10-16 13:58
Hi @mattwright @jimmyzhen @sgoehringer we reviewed the "secondary approver" specs in the Gene Curation Small group yesterday (@erinriggs @marinadistefano @jennygoldstein) and have made some adjustments which I will outline.

1) We would like to keep it to just one column for the approver list, but allow multiple choices from the EP/WGs currently curating. On the GCI Affiliation Approval v3 figure, part C, The approver(s) section should be the drop down list that allows multiple choices. We realized that there may some some instances in which more than two groups may want to curate and approve on a gene-disease relationship, especially syndromes in which multiple organs are affected. WE felt this might be the easiest way instead of adding more columns of approvers.

2) In the "GCI Affiliation Approval v3 figure.pdf", part E, the groups can use the approver comment section to outline the specifics on the approval process and and the group(s) efforts. 

[GCI Affiliation approval v3.pdf](https://github.com/ClinGen/clincoded/files/2483325/GCI.Affiliation.approval.v3.pdf)

3) For the Website recognition, we have provided a mockup, in which we would like the groups who contributed to the curation to be acknowledged in the "Expert curation" box. Further details of the approval and curation can be provided in the Evidence summary, which we will direct in the Evidence summary outline and SOP.

[Website dual recognition v2.pdf](https://github.com/ClinGen/clincoded/files/2483330/Website.dual.recognition.v2.pdf)

@sgoehringer For the website, we acknowledge point 1 and accept that there may be some overlap in the gene-disease curation records. We did discuss that it would be great to distinguish and display  the total number of approved gene-disease curations performed by ClinGen affiliated groups somewhere on the website.

For point 2, at this time how about we label them in alphabetical order for now.

We will make statement updates in the SOP coordinating with this change. Specifically that in cases in which multiple EPs/WGs want to contribute to the curation and/or approval that they must coordinate together for one entry in the GCI. We do not foresee the need to have the secondary group curate overtop of the current groups curation to add to the approval. This type of function will be reserved for groups that are "recruiting" and adding new information onto an existing curation and giving a new approval, not a joint approval.

Please let us know if you need anymore specs, or details.

Thanks @courtneythaxton

**Comment by wrightmw** [comment] 2018-10-24 14:55
@courtneythaxton 
@marinadistefano
@ErinRiggs
@jennygoldstein

So, following on from the call just now.  If you add EPs to the Approver(s) pulldown then you can specify them as the Approver (you can do this already). We could add the logic that if the Approver is an EP then this field is exported to the website (upon publishing). We would need to collaborate with the website team on this because the Approver field is not currently exported to the website.

Further, we could add an additional pulldown of Contributor(s). If Contributors are selected then these would be exported to the website (upon publishing). Because Contributors would be a new field then we would have to collaborate with the website team to show these.

You would need to specify with the website team how you would want the EP Approvers and/or Contributors to be displayed on the website.

I will be on the next small GCI WG call, so we can discuss this then also :-)

**Comment by ErinRiggs** [comment] 2018-10-24 15:01
?Perfect - adding in Scott so he is aware.  On the website end, we have previously discussed the desire to display the approving EP, though the desire to display contributers is new.  I think we can approach the display of these two things in a similar manner, though, so hopefully it won't be too difficult.


Scott, are you able to join us on our Gene Curation small group on Monday at 3p E?  Might be good to have everyone on together to discuss.


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by sgoehringer** [comment] 2018-10-24 15:10
Thank you for keeping me in the loop and I was aware that this was being considered.  Do we have a timeline (rough estimates are totally fine) on when the updates are expected in the GCI so we can work this into our development schedule?

Also, I can join a Monday call at 3pm to discuss further.  Please share the invite when you have a chance.

@courtneythaxton, @marinadistefano, @ErinRiggs, @jennygoldstein, @wrightmw

**Comment by courtneythaxton** [comment] 2018-10-24 15:11
Okay, I will work on a mock up for the Multiple contributors section at this point. It would be good to know @jimmyzhen @wrightmw whether a multiple choice, single drop down would work column would work, or whether we would need a separate dropdown for each contributor? Thank you all for your help and advice on this. 

@ErinRiggs 
@marinadistefano
@jennygoldstein

**Comment by jimmyzhen** [comment] 2018-10-25 09:49
@courtneythaxton @wrightmw,

At the very basic level, multiple selection in a single HTML `<select>` (aka dropdown) is supported. In this case, the user can select multiple options from the dropdown menu while holding down either the `Command` key (Mac) or the `Control` key (Windows).

The implementation I envision for this, from the UI and UX perspective, _might_ be something similar to the following:
![image](https://user-images.githubusercontent.com/6956310/47491125-09738c80-d7ff-11e8-8e4f-8eef07723c6a.png)

If needed, we can organize the contributors into 2 groups in one single dropdown, such as **expert panels** and **non-expert panels**.

**Comment by courtneythaxton** [comment] 2018-10-25 23:58
Thanks @jimmyzhen this is really helpful to think about, and glad that the multiple selection will work. I do think we will need to think about how many of these drop downs we want. 

I do agree that it seems that we would need a Contributing Expert panel and a Contributing non-expert panel that would distinguish the entities contributing to the curation, and we might also want at least one Approving EP drop down, but possibly a second one that would indicate another EP contributed to the approval. WE will sort this out in the next Small group call (@erinriggs @marinadistefano @jennygoldstein).

**Comment by wrightmw** [comment] 2018-11-08 22:08
@jimmyzhen VCI WG confirmed they are happy with the same functionality added into the VCI.

**Comment by courtneythaxton** [comment] 2018-11-13 14:48
I wanted to add the new mockup of the contributor and approver classification for the GCI modal. We discussed that the drop down menus for the contributor and approver should be the official affiliation names of the GCEPs, not individual names. As @jimmyzhen showed above, we would like both contributor and approver to have multiple choice selection.

I have also included an updated website display. I added a section to highlight the groups contributing to the curation, and created it as smaller text, that way the approval of the classification is the larger, more noticeable. 

let me know what you all think or if I should make any adjustment or if we need to discuss more specifications @ErinRiggs @Marinadistefano @jennygoldstein @wrightmw 

Thanks!
@courtneythaxton 

[Website dual recognition v3.pdf](https://github.com/ClinGen/clincoded/files/2576697/Website.dual.recognition.v3.pdf)
[Secondary Affiliation approval v5.pdf](https://github.com/ClinGen/clincoded/files/2576698/Secondary.Affiliation.approval.v5.pdf)

**Comment by marinadistefano** [comment] 2018-11-19 13:47
Thanks for doing this Courtney. This looks good. The only question I have is if we had decided that only one group or multiple groups would be the approver(s)? I only ask because you have multiple contributors, but it's unclear whether we would have multiple approvers (just because the dropdown text is plural)?


Marina


________________________________

**Comment by courtneythaxton** [comment] 2018-11-19 15:56
That is a good question Marina. I'm not sure it was exactly decided by the large group. I believe towards the end we felt that more than one approver would be nice, and would be used in a limited amount of cases. I do think there was some discussion on whether one affiliation should be able to add a secondary approval (as we have outlined), or whether it needs to be enabled in the GCI for two separate affiliation to approve the same GDM record under their own affiliations.


I believe for now our solution is the most straight forward, and I do not think multiple groups would “abuse” (for lack of a better word)  the ability to choose a second affiliation. Meaning I don’t think a group would choose a secondary approver without reviewing the classification first. However, I do think it should be confined to the ClinGen Expert panels to choose this option, and not for outside entities (such as counsel, illuminate, or the community).

What do others think?

Courtney

**Comment by courtneythaxton** [comment] 2019-03-19 01:49
Hi all,

I have outlined some specs for the multiple contributor and multiple approvers for a classification in the GCI (potentially to enable in the VCI), after the March 7 GCI/VCI call. Please see the attached word document. 

One suggestions was to provide a controlled drop down list of choices to indicate how "Contributors" contributed to the curation and/or classification. Help would be appreciated to populate this list. Some initial suggestions include: performed the curation, performed the procuration, provided evidence as an outside entity (e.g. Counsyl spreadsheets). 

@wrightmw 
@cgpreston 
@ErinRiggs 
@marinadistefano 
@jennygoldstein
@sgoehringer 
[Multiple contributor and approver specs_March 2019.docx](https://github.com/ClinGen/clincoded/files/2981147/Multiple.contributor.and.approver.specs_March.2019.docx)

**Comment by marinadistefano** [comment] 2019-03-26 16:00
Thank you for making this document Courtney. I think it overall looks good and is consistent with what we discussed. The only question I have (and maybe we can just discuss it again quickly on Monday's GCI call with Matt) is about the dropdown for contributor comments vs the free text and how that would work. Would it just be the dropdown text, the free text only, or both?

________________________________

**Comment by courtneythaxton** [comment] 2019-04-22 20:06
Hi All, After the Gene curation small call today, we felt that the use of the standardized drop down selection may not be readily used and therefore decided to go ahead with the specs uploaded here. In the future if the PIs really feel that we should include these standardized text we can work on them. At this point in time, the text in these boxes is not forwarded to the website team nor displayed on the curation summaries, and we would like for it to be maintained in that way.

thanks,
@courtneythaxton 

@marinadistefano 
@wrightmw 
@ErinRiggs 
@jennygoldstein
@cgpreston 
@markmandell 

[Multiple contributor and approver specs_v2.docx](https://github.com/ClinGen/clincoded/files/3104705/Multiple.contributor.and.approver.specs_v2.docx)

**Comment by wrightmw** [comment] 2019-08-09 04:48
@courtneythaxton
@ErinRiggs
@jennygoldstein

Can you please confirm the answer to this issue? Currently for many GCEPs, they have elected to have a small number of people who are "Approvers"... for instance, in the HL GCEP there are 3 Approvers... when someone goes to approve then they have select one of these 3 Approvers. These individual approvers are not made public. Do you still want these groups to be able to chose individual approvers? And would we want a selected secondary approver to be able to pick individual approvers?

**Comment by ErinRiggs** [comment] 2019-08-09 12:47
I think we would want the "main" group to continue to be able to approve things the way they normally would (i.e., if they normally select individual approvers, they should be able to select individual approvers here).  I don't think it is necessary to identify individual approvers for the secondary group.

**Comment by wrightmw** [comment] 2019-08-09 15:23
Thanks for the clarification @ErinRiggs :-)

**Comment by wrightmw** [comment] 2019-08-12 03:13
![](https://github.trello.services/images/mini-trello-icon.png) [Secondary Approvers/ Contributors](https://trello.com/c/dzFUGJid/21-secondary-approvers-contributors)

**Comment by markmandell** [comment] 2019-08-14 16:41
Here is the instance for this ticket: https://1796-mm-secondaryapprovers.demo.clinicalgenome.org/dashboard/

There seemed to a be a consensus to keep the "normal" classification Approver input, in addition to adding what was included in the spec. The additional info should be displayed in the Approval Preview, the Approval "snapshots" toward the bottom of the page, as well as the Evidence Summary. Let me know if there are any issues/feedback!

**Comment by courtneythaxton** [comment] 2019-08-16 00:04
Hi @markmandell @wrightmw 

This is looking good. I like the ability to expand or hide the screen. 

First note: The contributor vs Approver sections are unaligned, could we align them? (see pic)
<img width="1128" alt="Screen Shot 2019-08-15 at 7 54 16 PM" src="https://user-images.githubusercontent.com/32530005/63134291-d3beb080-bf96-11e9-9f5b-e4f69d9329d5.png">

For the approval summary in the GCI, I was able to add multiple contributor and approvers! See pic
<img width="1058" alt="Screen Shot 2019-08-15 at 8 01 12 PM" src="https://user-images.githubusercontent.com/32530005/63134488-96a6ee00-bf97-11e9-8f26-7242dc91e0df.png">

I believe that the GCWG set that the approving group has the responsibility for giving credit to the contributors and approvers outside of their affiliation. 

I did want to ask, for GDMs that may be transferred from a biocuration core, is there a way to highlight the contribution? This may be too much right now, and that is okay if it cannot be done, but thought I would ask

**Comment by markmandell** [comment] 2019-08-16 00:13
The unaligned inputs might be a browser issue, I'll definitely look into it and fix! I'll test it out to see. Just wanted to include a screenshot from the panel when I went to the same instance to show what it looks like on my end.

<img width="1165" alt="Screen Shot 2019-08-15 at 5 07 50 PM" src="https://user-images.githubusercontent.com/45801431/63134665-589dd000-bf7f-11e9-94da-f3b7ac1ab1bc.png">

I will also be sure to get with Matt and discuss highlighting the contributions, and I will take a look into that as well :)

**Comment by courtneythaxton** [comment] 2019-08-16 00:14
Thanks @markmandell IT may be my browser, I'm on my single, little Mac screen!

**Comment by wrightmw** [comment] 2019-08-16 03:13
@courtneythaxton 
1) Now that we have "Curation Approver(s)" it's confusing to also have the "Approver". How about we change "Approver" to something like "Individual Approver" or "Affiliation Approver" or something else to make the terminology distinct?
2) The button that opens up the form says "Open Contributor(s) Form", do you think it would be more clear if it said "Open Contributor(s)/Curation Approvers(s) Form"... but that's getting too long, so how about just "Open Attribution Form"?

**Comment by wrightmw** [comment] 2019-08-16 03:19
@markmandell This looks great. I noticed one error in the way this works. When you save an Approved record then on the classification page this sits above the provisional saved. When I migrate away and come back to the classification summary, then the Approval has disappeared.

**Comment by wrightmw** [comment] 2019-08-16 15:10
@courtneythaxton just reading through this thread, I noticed your question further up. The process shown within the UI is all about capture of these data. How it gets used for accreditation on the website is a downstream issue.  Currently in this v1 the record itself would remain a UNC biocuration core owned record if they created it. When selecting an Approver, you are just designating that they did the final Approval. If we sent the contributor and approver details to the website then they could credit the biocuration core there? Perhaps the contributor could auto-filled with UNC biocuration core?

**Comment by wrightmw** [comment] 2019-08-16 15:12
@courtneythaxton do you want the approvers to be all VCEPs/GCEPs as they are now listed, or should this just be GCEPs only?

**Comment by courtneythaxton** [comment] 2019-08-16 15:19
Hi @wrightmw @markmandell 

1. I agree to change the "Approver" to "Affiliation Approver"
2. I like the "Open Attributions Form"
3. I like the idea of the info button or hover over. I will work on this text with the small group.

4. Thank you for the downstream clarification. I was just wanting to consider when to get Scott G and Tristan in the picture, but most likely once we finalize this function before release.
5. Both VCEPs and GCEPs in the approvers list.

**Comment by wrightmw** [comment] 2019-09-24 19:32
Final Approval Date can be made required in a future release (see #2043)

**Comment by wrightmw** [comment] 2019-09-25 17:08
@sgoehringer When this ticket goes live (likely R29), then we'll have contributors/approvers to add to our JSON we provide to you. Can you please work with @markmandell to confirm what format you'd require these to be in within the JSON file, so that we don't break the pipeline by changing the file.

Also @courtneythaxton @ErinRiggs @jennygoldstein, if you want these data displayed on the website then you'll have to let Scott know how you want these to appear.

**Comment by wrightmw** [comment] 2019-11-27 17:32
Example of current application of this ticket:

![Screen Shot 2019-11-27 at 9 04 32 AM](https://user-images.githubusercontent.com/15131169/69745992-2fe9b280-10f8-11ea-9317-b4fd05f9648d.png)

There is now only one Curation Approver allowed. However, multiple Curation Contributors are still allowed.

On the large GC WG call today, it was suggested that the following text changes be made:
- "Curation Contributor(s)" change to "Classification Contributor(s)"
- "Curation Approver(s)" change to "Classification Approver"

Is that correct @ErinRiggs . Other than those text changes, I don't think there is anything else that needs to be done with this ticket (is that right?), so maybe we could sign off on this (after the text changes) and do the code review on it, and hopefully get this into the next release?

**Comment by wrightmw** [comment] 2019-11-27 17:34
@markmandell Text changes above would apply to the publication panel also.

**Comment by wrightmw** [comment] 2019-11-27 17:41
@markmandell @bryanwulf 
In most cases an affiliation would only have a "ClinGen affiliation" associated with it, and we export that to the streaming service/website. However, if the user selected an alternative Approver (note: currently on this mockup this is the "Curation Approver" but changing to "Classification Approver") then instead that should be the only one exported to the streaming service/website. That is, the default we export is the "ClinGen affiliation" unless an alternative Approver has been selected, and then we should export that. I suspect @sgoehringer would only want to receive one Approver from our output?

**Comment by markmandell** [comment] 2019-11-27 17:45
@wrightmw Sounds good, I'll make the changes and update the instance.

As for what's being sent to the website, it looks to me like we would be sending both. But if one needs to be prioritized over the other or we only want to send one approver, we can decide which is best!

**Comment by wrightmw** [comment] 2019-11-27 17:51
Thanks @markmandell 

@sgoehringer would you ok with us sending you both? And you would just display one of them?

**Comment by wrightmw** [comment] 2019-12-17 23:46
@bryanwulf @markmandell 
"Classification Approver(s)" used to be multi-choice with a type ahead functionality, but this field got changed by request to just a single "Classification Approver" and a pulldown was instituted instead. Finding the one you are looking for in the pulldown is not very user friendly because it's a long list (and will get longer) and they are not in any perceivable order. Would it be a quick fix to make this list alphabetical?

![Screen Shot 2019-12-17 at 3 42 42 PM](https://user-images.githubusercontent.com/15131169/71043735-6eb1cd80-20e4-11ea-90da-3235170b57c7.png)

**Comment by wrightmw** [comment] 2019-12-18 00:05
@markmandell The type ahead functionality is working for me now! So looks good.

**Comment by wrightmw** [comment] 2019-12-18 00:08
@markmandell @bryanwulf Will the contributors appear on the website once published? If not, then we still need to have an indicator to our users that this will appear at a later time.

**Comment by wrightmw** [comment] 2019-12-18 00:20
@markmandell @bryanwulf So, for instance... here where I've provided "Classification Contributors" there needs to be some text letting folks know that "Classification Contributors can be published but will not appear on the ClinGen website until  it has been updated to support this new field":

![Screen Shot 2019-12-17 at 4 11 53 PM](https://user-images.githubusercontent.com/15131169/71045189-f7326d00-20e8-11ea-9036-b01cfa70d30a.png)

@cgpreston Do you have any suggested tweaks for this message?

**Comment by cgpreston** [comment] 2019-12-18 00:31
@wrightmw, I suspect some people will be interested in knowing if the website will then retroactively show any Classification Contributors for curations published between this feature going live in the VCI and the website support for the field.

**Comment by cgpreston** [comment] 2019-12-18 00:35
If the website implementation is retroactive, maybe something like "Classification Contributors may be added and the curations published in the VCI now, the classification contributors will not appear on the ClinGen website until the website supports displaying this new field.".  If it's not retroactive then I think we need different language.

**Comment by sgoehringer** [comment] 2019-12-18 00:59
Support for the display will be retroactive.

**Comment by wrightmw** [comment] 2019-12-18 02:12
That looks great... here again with very minor tweaks:
"Classification Contributors may be added and then published in the VCI now, however classification contributors will not appear on the ClinGen website until the website supports displaying this new field.".

**Comment by courtneythaxton** [comment] 2019-12-18 02:24
Would you all consider this language?
"At present, designation of Classification Contributors is restricted to the VCI/GCI. In the future, Classification Contributors will appear on curation summaries published to the ClinGen website and/or ERepo to facilitate recognition."

**Comment by sgoehringer** [comment] 2019-12-18 03:47
I like the version Courtney shared.

**Comment by ErinRiggs** [comment] 2019-12-18 03:57
Scott, when do you anticipate this being available on the website?  If it is going to be lengthy amount of time, we may want to add something like: "In the interim, consider mentioning the Classification Contributors in the free text evidence summary to acknowledge their work."

Also, please use "Evidence Repository" instead of "ERepo" in case people don't know what that is.


Erin Rooney Riggs, MS, CGC

Assistant Professor

Certified Genetic Counselor

Autism & Developmental Medicine Institute

Geisinger

eriggs@geisinger.edu<mailto:eriggs@geisinger.edu>


________________________________

**Comment by wrightmw** [comment] 2019-12-18 04:40
Ok. Great. Thanks guys. Let's go with Courtney's text.

**Comment by wrightmw** [comment] 2019-12-18 04:44
But with "Evidence Repository" instead of "ERepo". So the text would be:

"At present, designation of Classification Contributors is restricted to the VCI/GCI. In the future, Classification Contributors will appear on curation summaries published to the ClinGen website and/or Evidence Repository to facilitate recognition.""

**Comment by wrightmw** [comment] 2019-12-18 04:46
But with "Evidence Repository" instead of "ERepo". So the text would be:

"At present, designation of Classification Contributors is restricted to the GCI. In the future, Classification Contributors will appear on curation summaries published to the ClinGen website and/or Evidence Repository to facilitate recognition."

**Comment by sgoehringer** [comment] 2019-12-18 13:20
Regarding Erin’s question....  I see Tristan later today and I can confirm timing because he is tasked with the work needed to consume the data into the service that the website utilizes for display.

**Comment by wrightmw** [comment] 2020-01-10 17:17
Added as part of Release 30 (R30)

**Comment by wrightmw** [comment] 2020-01-10 17:17
Added as part of Release 30 (R30)

**Closed by wrightmw** 2020-01-10 17:17 UTC
Labels: GCI, colleague request, dependency, priority: high
