### ISSUE TITLE
Change MONDO ID for DSP:ARVC GDM

### ISSUE THREAD

**Issue by courtneythaxton** [ClinGen/clincoded#2136] opened 2020-02-03 21:16 UTC
@wrightmw @cgpreston 

The ARVC GCEP is in need of updating the disease entity (MONDO ID) for the DSP gene curation: https://curation.clinicalgenome.org/curation-central/?gdm=0683943f-da80-4a3c-8f9f-454d59040eb2&pmid=23954618

The current MonDO is ARVC MONDO:0016587.

We need this changed to MONDO:0011581 (arrhythmogenic cardiomyopathy with woolly hair and keratoderma)

thanks
@courtneythaxton

**Comment by h-tong** [comment] 2020-04-10 19:17
Hi @courtneythaxton, I changed the disease for the DSP gene curation (as well as the disease for the associated evidence if it seemed appropriate).

I noticed the following have the disease **arrhythmogenic right ventricular dysplasia 8** (MONDO:0011831):

- The second article (PMID: 28527814), the first 6 individuals
- The fourth article (PMID: 12373648), the family and individual

I decided not to change it since it seems intentional, so I just wanted to let you know.

Please let me know if there are any issues!

**Comment by cgpreston** [comment] 2020-04-29 18:02
This was a patch to the R32 instance. Confirmed on production, thanks @h-tong closing this.

**Closed by cgpreston** 2020-04-29 18:02 UTC
Labels: EP request, GCI, curation blocker, curation edit, priority: high
