### ISSUE TITLE
Be able to add family to group, etc., retroactively

### ISSUE THREAD

**Issue by selinad** [ClinGen/clincoded#402] opened 2015-10-22 01:01 UTC
We need to model this and determine feasibility:

Ability to create a family and then add it to a group.  Similarly, create an Individual and add to Family or Group.

**Comment by kilodalton** [comment] 2016-01-15 22:31
Duplicate of #257 (Associate Individual, Families, Groups). Closing.

**Closed by kilodalton** 2016-01-15 22:31 UTC
Labels: active, external curator, R4
