### ISSUE TITLE
Pre-alpha2 Individual updates

### ISSUE THREAD

**Issue by forresttanaka** [ClinGen/clincoded#282] opened 2015-09-05 00:29 UTC
To fix minor issues with Individual curation between first and last alpha2 builds.

**Comment by selinad** [comment] 2015-09-05 00:54
Text on View Individual page has extra characters in it (for proband and non-proband Individual view)

![screen shot 2015-09-04 at 5 06 56 pm](https://cloud.githubusercontent.com/assets/11320314/9696844/bd97f1f6-532d-11e5-85ab-320ab6228774.png)

**Comment by selinad** [comment] 2015-09-05 15:45
Please change the term "VariantID" to "VariationID" in the following places:

* phrase "ClinVar VariantID" in the Variant sections 
* free text in Variant section
* View page field title
* Error check text (red text returned when ClinVar VariationID entered incorrectly according to checks)

**Comment by selinad** [comment] 2015-09-05 15:51
Please change "HPO browser" link in all locations for now to say:

"HPO lookup at Bioportal"
and link to: http://bioportal.bioontology.org/ontologies/HP?p=classes&conceptid=root

@forresttanaka - we could hold on this until confirmed by others in group, but this seems best from my perspective

**Comment by forresttanaka** [comment] 2015-09-06 00:57
HPO browser, ampersand, and VariationID changes her:

https://282-ft-prealpha2-7f15ff5-fytanaka.demo.clinicalgenome.org

**Comment by forresttanaka** [comment] 2015-09-06 07:36
With “Common” text update: https://282-ft-prealpha2-ef33b09-fytanaka.demo.clinicalgenome.org

**Comment by forresttanaka** [comment] 2015-09-06 17:15
#### Change Summary

* Change all visible occurrences of “VariantID” to “VariationID.” All variable names and the corresponding schema property stay with “variantId” for now to avoid too many changes.
* Change all [HPO Browser](http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118) links to [Bioportal](http://bioportal.bioontology.org/ontologies/HP?p=classes&conceptid=root) links for now, as at this time the HPO Browser doesn’t work. We can revisit this later. Change the corresponding link text to “HPO lookup at Bioportal“ and all link tooltips to “Bioportal Human Phenotype Ontology.”
* Changed “Common diseases” phrase to just “Diseases” on the Individual Curation, Edit, and View pages.
* Changed the ampersand in the “Diseases & phenotype(s)” page to use an actual ampersand in the text instead of the HTML entity code. The text used to be an HTML string, but recently changed to a Javascript expression where HTML entity codes become literal text.

**Comment by forresttanaka** [comment] 2015-09-06 19:22
Slight text changes: https://282-ft-prealpha2-ce5e150-fytanaka.demo.clinicalgenome.org

**Comment by selinad** [comment] 2015-09-06 23:48
Thanks, @forresttanaka - it is looking great
1-4 were fixed.
5 looked good.

Additional comments:
1. Family edit page panel header says "Variant(s) Segregating with Proband" but View page says "Variant(s) Associated with Proband" - change View page to what is on Edit page
2. For variant panels - for those that have the note "ClinVar VariationID should be provided in all instances it exists. This is the only way to associate probands from different studies with the same variant, and ensures the accurate counting of probands." - thinking this note should go below line (just on top of the box where one enters VariationID (that is, it doesn't show until you Add variant).  Also, some way to emphasize the text would be great - hesitate to say red...
3. I'm sorry, but could you change the text I already asked you to change:  Description of Methods by which specific mutations genotyped: ->  Description of Method(s):
4. Text on Group Submit page: "**Note**: Family Information includes any information about a proband in the group that is part of family and any relatives of the proband (e.g. presence of phenotypes, average age of onset, race, family ethnicity and/or any information about the segregation of phenotypes and/or variants) and/or any information about segregation e.g. de novo status." -> Note: Family Information includes any information about a proband in the group that is part of family and any relatives of the proband (e.g. average age of onset, race, family ethnicity, etc.) and information about segregation of phenotype(s) and variant(s)."
5. For the label headers re Disease & Phenotypes for Curate, View, Edit:
Group, Family: Common Disease(s) and Phenotype(s)
Individual: Disease and Phenotype(s)
6. For Individual, say "Orphanet Disease for Individual" rather than "Orphanet Disease(s)..."
7. Capitalize "individual" on Individual page in the Additional Information section (may be right for View and not Edit or vv).
8. View page for Individual [proband] says Variant(s) Segregating with Proband - should be same as non-proband individual as there is no segregation info.
9. For future unless trivial: Copy Orphanet ID button - could it be left justified with entry box?

If there is anything here not appropriate for alpha2, please feel free to move.  Thank you!

**Comment by kilodalton** [comment] 2015-09-07 00:19
@selinad  Thank you for looking at and thinking about what changes need to be made.

Because of the holiday weekend  we have very limited time to implement and test and apply an extensive array of changes to alpha2. 

With that in mind, please tell us which, if any, of the above changes would prevent a curator from proceeding.  Anything that is not blocking will be moved to a post-alpha2 ticket.

**Comment by selinad** [comment] 2015-09-07 03:52
Hi @kilodalton - I think alpha2 is in great shape.  As I mentioned, feel free to move anything to post-alpha2, or I am happy to do so. For some reason, I thought more testing was desired, but maybe it was just of the fixed features. 

None will prevent a curator from proceeding - @forresttanaka did an excellent job with a complicated workflow and set of relationships.

The only thing that is not technically correct is #8 - when an Individual is added to a Group but not a Family, there should be no segregating info, so the panel title is incorrect (https://282-ft-prealpha2-ce5e150-fytanaka.demo.clinicalgenome.org/individuals/2fe2f8a5-a7e0-47ac-a789-b81d3bc5e09e/) - definitely not a game stopper, though.

So, I leave it up to the devs as to whether you want to incorporate any of the above changes for alpha2.

**Comment by selinad** [comment] 2015-09-07 03:54
Also, @forresttanaka suggested I add item 2 to this ticket - again, not a game stopper if not changed, but if there are other changes, he said this one simple...and it's important to make the use of VariationID clear.

**Comment by kilodalton** [comment] 2015-09-07 18:52
Items not addressed in PR #283 will be moved to a post-alpha2 release ticket.

**Comment by kilodalton** [comment] 2015-11-01 01:20
Great job. Thanks for all your hard work to get the app to production.

**Closed by kilodalton** 2015-11-01 01:20 UTC
Labels: bug, merged, v0.5
