### ISSUE TITLE
Edit schema variant and related test data for VCI

### ISSUE THREAD

**Issue by kgliu0101** [ClinGen/clincoded#676] opened 2016-05-10 00:21 UTC
It's required to edit variant schema and test data for VCI as:

1. Add new property "carId".

2. Some ClinVar variants have multiple dbSNP ids. We need to change type of property dbSNPId in schema variant from string to array.

3. Change type of property hgvsNames from array to object for storing HGVS GRCh37, GRCh38, and others HGVS separately.

4. Change clinVarCRV from string to array, and add clinVarSCV.

**Comment by kgliu0101** [comment] 2016-05-10 19:25
@mrmin123, new variant schema and test data are in branch #676. Use variation id 55964 to review sample of hgvsNames (save RGCh37 , 38 and others separately). In test data,  CAR ids are added in variants 55874, 55962,  55964 and 55966. dbSNP ids are in variants 36485, 36753, 38601, 55847,  55874, 55962,  55964, 55966 and 55996. Let me know if you have any comment.

**Comment by mrmin123** [comment] 2016-05-10 22:19
@kgliu0101 My observations:

* I think you have a superfluous field `hgvsGRCh37` in the schema file, and `hgvsNames` has a description of 'Other HGVS Terms' but this doesn't seem correct now. I think just 'HGVS Terms' will do.
* Schema version should probably move up to 3, since they are not backwards compatible.
* These changes to the schema also necessitates an upgrade script.

**Comment by kgliu0101** [comment] 2016-05-11 01:00
@mrmin123 
* Edit the schema
* Add version update control
* Generate a new small dump file

**Comment by mrmin123** [comment] 2016-05-11 19:29
@kgliu0101 
The schema looks good now but the upgrade script needs work. It's a bit of work, but you need to add handling for converting fields that have changed from the old data type to the new data type, and for fields that are completely new, you need to specify a blank field of the correct datatype.

So, for a completely new field you have to do something like:
```
if 'carId' not in value:
    value['carId'] = ''
```

For fields with new names and/or datatypes you have to do something like:
```
if 'dbSNPId' in value:
    value['dbSNPIds'] = [value['dbSNPId']]
    value.pop('dbSNPId', None)
```
the first line to cast the old string value as a new list item under the new key name, and the second line to remove the old key entirely.

Please refer to the 'Updating existing schema' section of this page for more information:
https://github.com/ENCODE-DCC/encoded/blob/master/src/encoded/docs/schema-changes.md

**Comment by mrmin123** [comment] 2016-05-11 19:30
For the record, if the upgrade is done incorrectly, there is a chance that any existing variant object will be invalidated because it no longer conforms with the new variant schema.

**Comment by kgliu0101** [comment] 2016-05-11 22:22
Controls to handle carId, clinvarRCVs, clinvarSCVs and hgvsNames are added.

Instance with production data at: https://676-kl-edit-variant-schema-36e6f0c-kangliu.demo.clinicalgenome.org

**Comment by kgliu0101** [comment] 2016-05-11 23:09
above instance is terminated. Please use the one at https://676-kl-edit-variant-schema-ca40197-kangliu.demo.clinicalgenome.org

**Comment by mrmin123** [comment] 2016-05-11 23:19
@kgliu0101 @kilodalton The schema looks good and the upgrade script seems to work as intended on the production data. I think this branch is ready to merge.

**Comment by kgliu0101** [comment] 2016-05-11 23:35
thx @mrmin123

**Comment by kilodalton** [comment] 2016-07-20 06:17
Included in last release (R7alpha1). Nice job and thanks for your hard work.

**Closed by kilodalton** 2016-07-20 06:17 UTC
Labels: R7alpha1, release ready
