### ISSUE TITLE
Experimental Data Page (was Functional Data Page)

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#89] opened 2015-07-15 22:46 UTC
Need a page per specs for viewing and editing functional data as it applies to a GDM.

Note that the functional data is associated with the gene in a disease context, BUT we will need to query "all" functional data for a given gene (with disease factored out)

**Comment by selinad** [comment] 2015-07-16 06:01
I'm not sure disease will be able to be 'factored out,' if I am understanding this expression correctly - we will need to find all information associated with a gene upon a gene query, including functional info, but it will be need to be clear in which GDM(s) the gene information exists upon query. It's possible a piece of functional evidence could be used for the same gene associated with a different disease if the curator deems it truly independent of the first disease (perhaps this is what you mean by 'factored out')...the query should just make clear any existing GDM associations.

**Comment by hitz** [comment] 2015-07-16 17:42
this depends on functional sample data from #21

**Comment by selinad** [comment] 2015-07-29 21:42
At last week's small gene curation meeting it was decided that Functional Data will now be called Experimental Data, as an FYI for anything that needs to be updated.

**Comment by mrmin123** [comment] 2015-09-11 23:22
@selinad prelim version of experimental data curation page has been incorporated here: http://89-mc-experimental-data-page-70019d0-minchoi.instance.clinicalgenome.org/dashboard/

Added Experimental Data items can be seen here: http://89-mc-experimental-data-page-70019d0-minchoi.instance.clinicalgenome.org/curation-central/?gdm=a670526d-1b2b-41d6-bd55-2e0bca960171&pmid=123456

There are some bugs/improvements that I haven't managed to get in yet:
* Checkboxes look funky/out of place
* Some form interface stuff looks funky/bad
* When disabling text fields they're not cleared. I need to either fix/work around the function that is supposed to do this or just make sure that those values aren't passed into the database on form submit
* Genes aren't checked to see if they exist when submitting
* Genes don't show up when Viewing an Experimental Data object

### Some possible tests
1. Create GDM/Navigate to GDM
2. Select evidence
3. Add an Experimental Data type
4. Try viewing it
5. Try editing it
6. Repeat steps 3-5 for the 5 other different Experimental Data types

Corrections on the field names and messages would be much appreciated!

**Comment by selinad** [comment] 2015-09-15 01:23
Hi @mrmin123 - Here is some feedback based on preliminary testing. Again, a lot of great work!
I will edit this comment tomorrow as I have more things to add....

**Note**: Variant entry field needs to be added where specified on pptx - do this based on variant info on Family page

**Functionality changes**
- Have Experiment Name field come AFTER pull down for experiment type - will be easier for a curator to name an experiment after specifying type 
- On the View page - the experimental evidence type should be in the title rather than the gray box for consistency with other View pages
- I'd like to discuss putting the GO Slim terms in a pull-down - linking externally is difficult and will produce error (there are 90ish terms)
- Left justify A and B on the relevant pages and maybe make font a bit bigger - these should seem like sections.
- On Submit pages, show type of exp data - e.g.
   Biochemical Function
   Experimental Data: [name]
- On Submit pages, provide the following buttons: 1) Add another piece of Experimental Data and 2) Return to Record Curation page [this should match the wording @forresttanaka uses]
   

**Text changes**
- On Edit page - put e.g. "Biochemical function" above the Experiment name in the title (rather than in parentheses) - maybe even make the font a bit bigger
- At top of page where there are A and B - we need to add text explaining this - too confusing.  I will write this out.
- On BF- A (Biochemical Function) page, instead of "Evidence that other gene(s) have the same....", put “Evidence that above gene(s) share same function"
- For all exp evidence types, use the phrasing "“Notes on where evidence found in paper" rather than "Information about where evidence can be found in paper"
- where checkbox exists (BF): we need to add text just under it  "Note: If the other gene(s) have not been implicated in the disease, the criteria for counting this experimental evidence has not been met - proceed to B or cancel" (but we don't have cancel, so maybe "...or return to Record Curation page"
- BF- A: “Explanation of relationship of other gene(s) to disease…” ->  “How has this gene(s) been implicated in the above disease”
- BF- B: Mimic other HPO field titles (see Group, Family etc. page)

**Bugs**
- on BF page, see "Shared disease (Orphanet): 1 (where both are in regular, not bold font, and there is no entry box):
![screen shot 2015-09-14 at 6 02 20 pm](https://cloud.githubusercontent.com/assets/11320314/9865417/c77a693a-5b0a-11e5-8dc1-ccb33ccdb75e.png)
- View page for Rescue data from Submit page gives following error: 
Server Rendering Error

The server erred while rendering the page.

TypeError: Cannot call method 'toString' of undefined
    at [object Object].React.createClass.render (/srv/clincoded/src/clincoded/static/components/experimental_curation.js:1579:83)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].wrapper [as _renderValidatedComponent] (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at [object Object].wrapper [as mountComponent] (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/srv/clincoded/src/clincoded/node_modules/react/lib/ReactDOMComponent.js:199:12)

**Comment by mrmin123** [comment] 2015-09-16 23:25
@selinad : http://89-mc-experimental-data-page-175838c-minchoi.instance.clinicalgenome.org/ (live as of 2015-09-16)

Everything with a green checkmark above has been fixed/addressed as of 175838c (above instance)

I'll be doing live testing now as well...

Things still not yet addressed are as follows (taken from both @selinad's and my previous post) - my comments are in italics:

**Functionality**
* Genes aren't checked to see if they exist when submitting form
* Genes don't show up when Viewing an Experimental Data item
* GO Slim terms in a pull-down - :question:*is this required for 0.5?*
* If we pull GO-Slim in, could we show term name (rather than ID) on the View page? - :question:*is this required for 0.5?*
* I need to get you CL terms....
* For the phenotype entries - tricky - we need to collect phenotype, but we only require one or the other for HPO vs. free text (not both). This is for all instance of phenotype collected for all evidence types.
* R: Does the wild-type rescue the above phenotype? -> required field (but next question is not); Also, let's put above "Method used to rescue: "  - :question:*should I make this a No Selection/Yes/No dropdown? Checkboxes inherently can't be required (or are inherently required, depending on how you look at it) because when unchecked there's no way to discern between no user input and user 'selecting' "No"*

**Comment by mrmin123** [comment] 2015-09-18 18:14
Updated instance (as of 2015-09-18): http://89-mc-experimental-data-page-9412ba1-minchoi.instance.clinicalgenome.org/

Previously instances have been taken down.

**Comment by selinad** [comment] 2015-09-18 18:37
Thanks, Min - I will get to this this afternoon.

**Comment by selinad** [comment] 2015-09-19 01:10
Super job checking off all of those items, @mrmin123!

I am going to comment by evidence_type:

Biochemical Function and Expression (A and B types)
* Could you please put the note about the 2 types of evidence at the Top of the section instead of bottom, now that I see how it is divided (so sorry) - you will have to say "Fill out this section and then curate...." (not top section).  Thanks for changing sections up - much clearer!  Kinda wonder if Biochemical function section should be gray (label area) rather than blue and not collapsable....it is necessary for other 2...maybe @forresttanaka has opinoin

* @forresttanaka - what do you think about bold for Biochemical Function (maybe my sugestion)  - thinking better to make that whole row a bigger font and get rid of bold, but would seek your styling advise to consistent.

* Can the description of the evidence type (thank you for adding!) go in one of those yellow/green boxes used in explaining Variant IDs? Would be nice to make more obvious.

* A. "Genes (HGNC):
 - link HGNC like @forresttanaka does
 - change to "Gene(s) with same function:"

* A. Orphanet should be linked as in rest of interface

* A. Asterisk only appears for "Evidence that gene(s) share same function once gene symbol entered above....seems strange

* A. Shared disease (Orphanet) - not editable and filled in with gene name (DICER1) right now:
![image](https://cloud.githubusercontent.com/assets/11320314/9973825/ce2b9d86-5e2e-11e5-9f4a-f928663c93b6.png)


* Ugh - sorry, @mrmin123 - please change Note on A to: "Note: if the gene(s) entered above in this section have not...."

* On this same note - "Curation Central" should be "Record Curation page"

* A. I think we need another note - at very bottom of section A: You may submit now by scrolling to bottom of page OR enter a new piece of biochemical function evidence in B, below.  

* It is necessary to add Associated Variants to each section - different variants can go with A vs. B. 

* Because of above change, if possible, is there a way to Save for each section?  I'm thinking no - how about a skip to save button for A?

* check with @forresttanaka as to "Submit" vs. "Save" buttons

* For Variant, they can enter only one or other - VariationID or Other Description - so, typing in one should prevent typing in other (see @forresttanaka variant info)

* Thanks for the note for variant section!  Modification:
If your experimental data is about one or more variants, please add these variant(s) below.
(use "experimental" instead of functional and no need to list evidence types here)

* capitalize "experimental" in "Add another variant...." button.

* something funny happening with gray and white for boxes....sometimes go gray, but then I can still edit...maybe after trying to submit with error?

* double check error reports - if do not 

* On VIew page - thinking it should read:
View Experimental Data: [name]
Biochemical Function

* View page should probably have A. or B. in front of section.  e.g. A. Gene(s) with same function....

* B. Great on requiring phenotype on one page or other!

* Got an Aw, Snap! when tried tp add B - could be due to instance....when I went back and tried again, it did it, although slowly.

* Just realized problem - we need different name for A vs. B evidence... @kgliu0101 should be counted these A as one piece, B as one piece....I'm sorry this has been so confusing.

**Comment by selinad** [comment] 2015-09-19 01:18
PROTEIN INTERACTIONS

* HGNC should link to HGNC 

* Change "Curation Central" to "Return to Record Curation page" as in previous

* Change **"Explanation of relationship of other gene(s)..."** -> **"Explanation of relationship of interacting gene(s)."** (sorry again!)

* Variant should just go in the Protein Interactions section

* Seems like variant box is working correctly for Interaction and not for Biochem Function

**Comment by selinad** [comment] 2015-09-19 01:40
EXPRESSION

* Same change wrt placement of note about A and B in top section (change wording and location)

* All changes that applied to Biochem Function wrt A and B apply - they are separate pieces of evidence (e.g. each need a name, separate variant entry for each, etc.).  Same comments for View page as well (e.g. add A. and B. in label sections, title changes, etc.)

* Put definition of evidence type in Edit section for all evidence types

*URL for Uberon still points to Bioportal on the Expression page rather the Uberon URL in earlier comment.

**Comment by selinad** [comment] 2015-09-19 01:44
FUNCTIONAL ALTERATION

* Variant should be included in main section (as with others) - we can discuss with @forresttanaka , but I think this makes sense.

* Working well!  I need to get you CL - should have time to do this wekeend (and get you GO- slim terms)

* Same comments for View and Edit pages as for other types

**Comment by selinad** [comment] 2015-09-19 02:00
MODEL SYSTEMS

* The HPO and free text phenotopyes cannot both b e required (for model system phenotpye and patient phentoype) - just one or the other for each (model system, patient)

* Need to check on cell-culture tpye/line and whether it is controlled vocab.  Made note to self.  Right now, it is all caps. BUG - enter text into Cell-culture tpye/line and get no submit when I hit save (happens in new or edited entry).Is there a required data type here?

* again, same comments apply re vairant , View, Edit 

* If user changes from animal model to cell-culture (or vv) in Edit mode - shoudl it erase other fields?  Not sure.  Could we have red text appear! "Please check that alll following fields still apply."

**Comment by selinad** [comment] 2015-09-19 02:07
RESCUE

* example EFO term for ontologies (although I need to check on CL)

* Only 1 of HPO or free text required.

* Change **"Method used to resuce"** -> **"Description of method used to rescue"**

* Ned check box rather than Y/N for the "Does the wild-type rescue the above phentoype"  Right now, allowed to save if enter NO.

* same comment with respect to "Curation Central"

* Variant box cdoes not work right on this one (either VariationID or Other Description required)

**Comment by mrmin123** [comment] 2015-09-21 18:35
@selinad, this is regarding this item:
* Can the description of the evidence type (thank you for adding!) go in one of those yellow/green boxes used in explaining Variant IDs? Would be nice to make more obvious.

![image](https://cloud.githubusercontent.com/assets/4326866/10000930/fd299b34-6053-11e5-9ad9-d423569c8734.png)
I chose blue because that's the 'info' color, but it's an easy change to yellow/green. Also, should I move the info box to immediately after the Experiment type dropdown? The potential issue with that would be that the location of the Experiment name field would move up and down depending on what is chosen in the previous dropdown. Am I making sense?

**Comment by selinad** [comment] 2015-09-21 19:16
Looks good, @mrmin123 !  I defer to you and @forresttanaka as to whatever color makes sense wrt the interface - I like the blue, though, and it does seem to be most consistent with where blue is in the resto f the interface.

I think the box is OK as is...it will always be close to the type since what is between it and the type is always the same (the name box) - thank you for checking, though.  Looks nice.

**Comment by mrmin123** [comment] 2015-09-22 18:16
@selinad Regarding the header, how does this look?:
![image](https://cloud.githubusercontent.com/assets/4326866/10026574/6350d864-6117-11e5-9965-7a434eb29924.png)

Other notes:
> **Biochemical Function A**: Asterisk only appears for "Evidence that gene(s) share same function once gene symbol entered above....seems strange
This is because if the field is always set to required, even if the user wants to submit information only for section B, the form will error out because they will be expected to enter 'Evidence that gene(s) share same function', even if they haven't specified a gene. I could disable requirement for the field entirely, if that's what you prefer.

> **All types**: For Variant, they can enter only one or other - VariationID or Other Description - so, typing in one should prevent typing in other
We briefly talked about this and I noted this above, but I can't manage to reproduce this, but I'll keep an eye out for it. If you manage to reproduce this in a future instance perhaps you can recount the steps you did (may involve form erroring and/or changing of experiment Type??) or show me?

**Comment by selinad** [comment] 2015-09-22 23:07
Hi @mrmin123  - yes the title looks great!

Thanks for the explanation - the field needs to stay as required, so no problem.

I'll let you know if I reproduce the problem - if it is working right for you, that's great!

**Comment by mrmin123** [comment] 2015-09-23 17:18
> **Model Systems**: Need to check on cell-culture tpye/line and whether it is controlled vocab. Made note to self. Right now, it is all caps. BUG - enter text into Cell-culture tpye/line and get no submit when I hit save (happens in new or edited entry).Is there a required data type here?

The schema says it should be EFO ID, so I'll set it to that... the submit not working is a separate bug I'll have to resolve.

**Comment by mrmin123** [comment] 2015-09-24 20:35
@selinad Working on the new behavior for the blue boxes:
![image](https://cloud.githubusercontent.com/assets/4326866/10086000/e139d1c2-62c0-11e5-8842-eb54865838d0.png)

It looks kind of weird to me with the information in the blue box being almost the same as the text in the dropdown right below it. Is this what you had in mind?

**Comment by selinad** [comment] 2015-09-24 21:59
Thanks, Min - I think it's OK - it just verifies they've selected the correct item and it gives them an easy visual to remember what they are curating towards.  

This is different for A, right, where the description for A is longer than the pull down wording.
The other option would be to put the select A or B pull down above the blue boxes - then the correct one shows after selecting from the pull-down - would this be more consistent with the other evidence types?

**Comment by mrmin123** [comment] 2015-09-24 22:11
@selinad I think this works. The other evidence types also have the text in the same location:

Biochemical Function:
![image](https://cloud.githubusercontent.com/assets/4326866/10088224/2beb51a2-62ce-11e5-840b-c7d25f7647a6.png)

Biochemical Function w/ A selected:
![image](https://cloud.githubusercontent.com/assets/4326866/10088230/390d560a-62ce-11e5-820a-7a28532fcb99.png)

Biochemical Function w/ B selected:
![image](https://cloud.githubusercontent.com/assets/4326866/10088237/47fc68c2-62ce-11e5-85d8-47f775aea218.png)

Protein Interaction:
![image](https://cloud.githubusercontent.com/assets/4326866/10088244/524dbb00-62ce-11e5-9f54-febd7520f48d.png)

Expression:
![image](https://cloud.githubusercontent.com/assets/4326866/10088249/5c758946-62ce-11e5-9f0d-630b6f91fbe7.png)

Expression w/ A selected:
![image](https://cloud.githubusercontent.com/assets/4326866/10088253/67223d62-62ce-11e5-931a-9e74f281bb1e.png)

Expression w/ B selected:
![image](https://cloud.githubusercontent.com/assets/4326866/10088263/704933c8-62ce-11e5-8474-a5fef38ae332.png)

Functional Alteration:
![image](https://cloud.githubusercontent.com/assets/4326866/10088268/78cc6826-62ce-11e5-9255-a9c7615627fe.png)

Model Systems:
![image](https://cloud.githubusercontent.com/assets/4326866/10088269/8224f384-62ce-11e5-9da4-624df50c5e8d.png)

Rescue:
![image](https://cloud.githubusercontent.com/assets/4326866/10088275/8c370880-62ce-11e5-9e51-7066d17845d9.png)

**Comment by mrmin123** [comment] 2015-09-24 23:36
@selinad & @tsneddon:
Instance of latest build (as of 2015-09-24): 89-mc-experimental-data-page-14def68-minchoi.instance.clinicalgenome.org

Has a bunch of the changes marked above.

Some things that I forgot about/are still missing:
1. Assessments
2. Some of the forms shouldn't be submittable when certain criteria aren't met. Specifically:
  * `Has this gene or genes been implicated in the above disease?` must be checked in Biochemical Function and Protein Interaction
  * `Is the gene normally expressed in the above tissue?` must be checked in Expression subtype A
  * `Is expression altered in patients who have the disease?` must be checked in Expression subtype B??? (need confirmation)
  * `Does the wild-type rescue the above phenotype?` must be checked in Rescue

If I'm mistaken on item 2 above let me know.

**Comment by selinad** [comment] 2015-09-25 00:02
Hi @mrmin123 Nice job and thanks - this looks great! 

How do you mark which type of Biochemical Function or Expression shows on palette? Maybe: Biochemical Function - A
Biochemical Function - B
or
Biochemical Function (A)
Biochemical Function (B)

**Comment by selinad** [comment] 2015-09-25 00:55
Thanks @mrmin123 

My comments on this instance for the Biochemical Function evidence-types A, B

Features:
* On first page when you click on Experimental, add instruction above: "Select which experiment type you would like to curate:"
* On the powerpoint, we were hoping to show the definitions of all the evidence types - would it be possible to show all of them in a big blue box and have them disappear when a selection is made?  If the evidence type is bolded and there are spaces in between, I think it should be legible (not necessary for beta if too much)
* Note above GO term box: To select a GO_Slim ID click on the GO_Slim link and copy/paste the desired GO ID into the box below. 
* When you select A., can the blue label you get say A. Biochemical Function instead of just Biochemical Function?
* BF-A and BF-B: Change "Identified Function" to "Identified function of gene in this record"
* BF-A and BF-B: Change "Evidence for Function" to "Evidence for above function"
* BF -A: Change "Gene(s) with same function" to "Other gene(s) with same function as gene in record"
* BF-A: Change "Evidence that above gene(s) share same function" to "Evidence that above gene(s) share same function with gene in record"
* For all places where the checkbox is not checked, is it possible to return to fresh Experimental Data page with ability to select an evidence type? (instead of the Record Curation page) - I'm sorry, I should have thought of that earlier.  Or, we could put both -"Curate New Experimental Type" or "Return to Record page"
* BF-A: change "How has this gene(s) been implicated in the above disease?: to How has this other gene(s) been implicated in the above disease?" (ugh - not quite sure how to handle the plural)
* Check for consistency in titles on Submit page - should Biochemical Function go below the Experimental Data Information?  See View page. On both pages, I think Biochemical Function should be in smaller font.  I like the way the Edit page title looks!
BF-B: Change to: "Phenotype(s) consistent with function" (for both HPO and free text titles)

Bugs/necessary changes:
* Remove the "There are 2 kinds of evidence that support biochemical function note..." (Bioch Function and Expression for both A and B selections)
* BF-A Remove note at bottom that says "Note: You may submit now by scrolling to bottom of page...." (for Bioch Function and Exp)
* Variant box should not be on Biochemical Function evidence type page
* BF-B - Great on phenotypes boxes.  I think we need to put in a note: "Either an HPO or free text Phenotype" is required."  Could go just above the HPO Phenotype box.
* BF-B: If edit and remove phenotype, info in boxes below (explanation of how phenotype consistent...) get erased - could they stay, but save gives error? (this may be impossible, but we should think of a solution for a later version as people might get annoyed if they lose their thoughtfully added descriptions! :-)

**Comment by mrmin123** [comment] 2015-09-25 17:17
@selinad How does this look for the palette?

![image](https://cloud.githubusercontent.com/assets/4326866/10107230/93560af8-636e-11e5-88b9-2867e382ad4a.png)

**Comment by selinad** [comment] 2015-09-25 18:01
Hi @mrmin123 

Thanks!  I'm just looking at the palette for Family, etc.  The bold is the label (name) for the Family (which the curator provides.

Maybe it should be:
**BFA1**
Biochemical Function (A)
*Minyoung Choi*
*Date*
etc.

This has the disadvantage of making it even longer vertically, but it is more consistent.  Either that, or we leave the type off, but I think users will want to scan since they are worth different amounts wrt the score

**Comment by mrmin123** [comment] 2015-09-25 18:08
Updated:
![image](https://cloud.githubusercontent.com/assets/4326866/10108353/4664b6d4-6375-11e5-874c-e6938a16a487.png)

Also, is this what you had in mind for the info box with all the definitions?:
![image](https://cloud.githubusercontent.com/assets/4326866/10108424/aa778782-6375-11e5-8275-ff4e92335128.png)

The box disappears when you select a Experiment type, and reappears if you set it to None

**Comment by selinad** [comment] 2015-09-25 18:18
Sweet.  I like that better wrt palette.

Yes - thanks - just 2 things:

1.  Add space between the different types so easier to read
2. Put blue box below Experiment type pull-down if easy to rearrange.

**Comment by selinad** [comment] 2015-09-25 18:34
Comments for Protein Interactions:

Features:
* Same comment about adding link to new Experimental entry page for note associated with a checkbox

Bugs/necessary changes:
* I'm sorry for the confusion, which seems to be on the pptx - variants should not be included for Protein Interactions.

**Comment by selinad** [comment] 2015-09-25 18:47
Comments for Expression

Features:
* EXP-A: Would it be confusing to do this for the Uberon example in the entry box: E.G. UBERON_0015228 (heart); if so, perhaps we should have a mini note: Search Uberon for an organ type (e.g. heart = UBERON_0015228). [Uberon hyperlinked here as in title]
* EXP-A: Let's change the title "Notes on where evidence found in paper" to be "Notes on where evidence found" - for this type of data, it could be somewhere besides a paper.

Bugs/necessary changes:
EXP-A: again, apologies for the confusion - EXP-A does not need Variant (EXP-B DOES need it)
EXP-A: change Curation Central link in Note to Record Curation page (as in other notes under checkboxes), + add getting back to experimental
EXP-B: Need note that follows check-box, with update to get back to new experimental data entry page.  Note would say: If the expression is not altered in patients who have the disease, the criteria for counting this experimental evidence has not been met and cannot be submitted. [then sentence I had reworked before for returning to add new experimental or return to record curation page]


We should think of adding Associated Variant to the Experimental data info on the palette - let me know if I should push to later version.

**Comment by selinad** [comment] 2015-09-25 20:03
Comments for Functional Alteration:

Features:
* As for Uberon, for CL and EFO and GO, would be nice to have examples, maybe just underneath box
 - e.g. fibroblast, CL_0000057 (under Patient type)
 - e.g. HepG2, EFO_0001187 (under Engineered equivalent)
 - e.g. DNA metabolic process, GO:0006259 (under normal function of gene...)
* Does it work to get rid of Engineered equivalent entry box if Patient cell type not entered or vv? Might be a little clearer to user.

Bugs/Necessary Changes:
* Change the evidence type read-out on palette to say Functional Alteration (rather than "Functional Alteration of gene/gene product")
* Also on palette and on page titles - prefer that an evidence type with 2 words have both capitalized (e.g. Biochemical Function, Functional Alteration)

**Comment by selinad** [comment] 2015-09-25 23:57
Model Systems:

Features:
* after pulling down animal model vs. cell culture, remove unselected option (as we discussed for Functional Alteration)
* Change "Patient phenotype" to "Human phenotype(s)" for both HPO and text boxes
* Change "Phenotype observed in model system" to "Phenotype(s) observed in model system" 
* Change "Explanation of how model system....in patient" to "Explanation of how model system....in humans"
* On View page - the order is different than on Edit page - rework to be the same order.  Also, change
Phenotype HPO observed-> Phenotype(s) observed in model system HPO
Phenotype observed in model system -> Phenotype(s) observed in model system
Patient phenotype HPO -> Human phenotype(s) HPO
Patient phenotype	-> Human phenotpye(s)
[note order above]
* In general, check that View page ordering matches Edit page

Bugs/Necessary Changes:
* Just noticed this - Experiment name should reset if Experiment type changed

**Comment by selinad** [comment] 2015-09-26 00:05
Rescue

Features:
* As for similar situations: after pulling down patient cell vs. engineered equivalent, remove unselected option (as we discussed for Functional Alteration)

Bugs/Necessary Changes:
* Sorry, you may have asked this earlier - for "Does the wild-type rescue..." - if not clicked, the boxes below need to be marked as non-editable (the "does patient variant rescue id is not required)
* On note , add the blurb about returning to adding new experimental evidence ("Add another experimental data entry" is what is on the button of the Submit page)

**Comment by mrmin123** [comment] 2015-09-28 17:54
@selinad @tsneddon 
New instance with above changes:
http://89-mc-experimental-data-page-c853eea-minchoi.instance.clinicalgenome.org/

I'm thinking of pushing assessments to another ticket/PR to keep the additions and changes somewhat isolated...

**Comment by mrmin123** [comment] 2015-09-29 00:12
Forgot to patch this in the last instance. Variants showing up in the Experimental Data palette:

![image](https://cloud.githubusercontent.com/assets/4326866/10152142/f4965cf4-6603-11e5-910c-3786fd66d638.png)

If you'd like a new instance with this change in let me know and I'll spin one up.

**Comment by selinad** [comment] 2015-09-29 01:51
Hi @mrmin123 - Wow - incredible work!!!  A lot of details to work through - thank you!

I'm not sure how our signals were crossed on this - I'm sorry if it was my fault.  Variant needs to be added to the following:
* Functional Alteration
* Model Systems
* Rescue

All the other changes you put in look great and I couldn't find any real bugs!  I have a few texty things, but I will review with Tam (these will not prevent pull request).

**Comment by mrmin123** [comment] 2015-09-29 16:15
@selinad The thing with Variants is actually a bug in my code! To be sure, however, Variants SHOULD be visible on:
Expression (B)
Functional Alteration
Model Systems
Rescue

Is this correct?

**Comment by selinad** [comment] 2015-09-29 16:18
@mrmin123 

Yes, correct!  Ah, good- hopefully it's an easy bug :+1: to fix!

**Comment by mrmin123** [comment] 2015-09-29 16:32
@selinad Yep, fixed now. I'll go ahead and make a PR now if that sounds good to you.

**Comment by selinad** [comment] 2015-09-29 16:46
I was happy with it, but if @tsneddon has a chance to run through it and make sure I didn't miss anything functional, that would be great.

**Comment by tsneddon** [comment] 2015-09-29 16:47
I just worked through it and didn't see any issues.

**Comment by selinad** [comment] 2015-09-29 16:47
Woot!  Thanks, @tsneddon; Nicely done, @mrmin123

**Comment by mrmin123** [comment] 2015-09-29 16:49
Great, will put together a PR ASAP. Thanks @selinad and @tsneddon!

**Comment by kilodalton** [comment] 2015-11-01 00:26
Great job. Thanks for all your hard work to get the app to production!

**Closed by kilodalton** 2015-11-01 00:26 UTC
Labels: merged, new UI feature, v0.5
