### ISSUE TITLE
Group Curation Page

### ISSUE THREAD

**Issue by hitz** [ClinGen/clincoded#6] opened 2015-06-08 23:03 UTC
Page for attaching HPO and other phenotype ids, free text., physical characterizations of the group.
Curators can add a label to it.

Ideally Ontology -> Look up terms (look up by ID and term name).

Right hand is navigation for display of subsections (Disease & Phenotype, Characteristics, Probands, , Methods

Need lists of drop-down values.

**Comment by hitz** [comment] 2015-06-08 23:28
Group page has a Family / Individual forkerator interface where you can assoiciate either individuals or families with groups.

**Comment by hitz** [comment] 2015-06-08 23:32
Needs to have mechanism for entering multiple phenotype ontology terms.

**Comment by hitz** [comment] 2015-07-15 22:31
Does this ticket include all the back end work to hook up groups -> GDMs via articles or should that be a separate ticket?

**Comment by forresttanaka** [comment] 2015-07-22 00:11
Group editing page functionality is done. Taking the first steps to the View Group page. I was able to use the content_views registry, so all this is is a view of a group object. To see the JSON for that group object, you now have to add **format=json** to the query string.

![screen shot 2015-07-21 at 17 09 02](https://cloud.githubusercontent.com/assets/1181324/8815252/3df3aeb6-2fcb-11e5-81f1-65038ef14e2e.png)

**Comment by forresttanaka** [comment] 2015-07-22 00:14
Left to do before issuing a PR for this issue:

* Style the Group View page.
* Do more edge-case testing of Create Group page.
* Implement Edit Group page as a variation of the Create Group page.
* Implement the CuratorPallette Group panel links for viewing and editing pages.

**Comment by forresttanaka** [comment] 2015-07-22 00:23
Transitioned to the clinicalDisease being an array instead of a single entry. Now allowing multiple comma-separated ORPHAxxxx entries into that field, as well as the otherGenes field. If any entered diseases or genes don’t exist, an error message appears on those fields, and the form can’t be submitted to create a new Group.

![screen shot 2015-07-21 at 17 17 44](https://cloud.githubusercontent.com/assets/1181324/8815361/df0a5fa6-2fcc-11e5-917c-9b043e2d8d79.png)

![screen shot 2015-07-21 at 17 23 00](https://cloud.githubusercontent.com/assets/1181324/8815385/2a4fc8a2-2fcd-11e5-99e5-943247a52171.png)

**Comment by selinad** [comment] 2015-07-22 01:01
Great!  I assume it doesn't matter if there are spaces after the commas and before the next term...?

**Comment by forresttanaka** [comment] 2015-07-22 01:03
It’ll take spaces between terms (even lots of spaces), and before and after the whole thing, without hurting the parsing.

**Comment by selinad** [comment] 2015-07-22 01:04
awesome.  Thx, Forrrest.

**Comment by selinad** [comment] 2015-07-22 01:22
Wording changes:
* [checking on "Diagnosis" terminology]
* [checking on whether we can say "Shared Phenotypes"]
* for proband information - last entry -> user should be able to enter multiple HGNC terms (comma-separated)
* Under Additional Information.  Change "Add any other PMID(s)..." -> "Enter PMID(s) that report evidence about this same group"  (sounds a little more serious, and this is important). This should allow entry of multiple PMIDs, separated by comma.
* Additional Information - Note: change to read: "Any variants associated with probands that will be counted towards the Classification are not captured at the Group level - variants and their association with probands are required to be captured at the Family or Individual level.  Once you submit the Group information, you will be prompted to enter Family/Individual information."  

Is there a way to make the page scroll when you open one of the sections?  Otherwise, the opened section is hidden (not necessary for 0.5).

**Comment by forresttanaka** [comment] 2015-07-22 01:26
* Oh! Yes, that should be HGNC, not symbol. I’ll change that.

The rest sounds fine.

**Comment by selinad** [comment] 2015-07-22 15:44
I think you could leave the "Other genes found to have variants in them" text and put the "e.g. DICER, SMAD3" as example text in the box...

**Comment by forresttanaka** [comment] 2015-07-22 15:47
Wait, does HGNC:XXXX go in here or gene symbols like “DICER1” and such? I have gene symbols working there now, but I wasn’t paying enough attention to your PPT there.

**Comment by selinad** [comment] 2015-07-22 15:48
Should be the gene symbols - that is what we have when we create a GDM, and what is most meaningful to the curator.  thx for checking!

**Comment by forresttanaka** [comment] 2015-07-23 21:17
Curator Palette (as I call it) on the Curation Central page. For now, I removed Family, Individual, and Functional — we know what they’ll look like.

![screen shot 2015-07-23 at 14 16 05](https://cloud.githubusercontent.com/assets/1181324/8862441/6556b36a-3145-11e5-9383-d70c395aeec2.png)

**Comment by kgliu0101** [comment] 2015-07-23 21:24
is it necessary to show group label?

**Comment by selinad** [comment] 2015-07-23 21:31
Nice!  Small stylistic suggestions:
* Would the white text in gray box look crisper if not bolded? (not sure) 
* Thinking we might want a pipe (|) between "View" and "Edit" (View | Edit) - question for 0.5 - will both functionalities exist or will they be the same?  (e.g. you view but are allowed to edit).

Kang, showing the label will be helpful to the curator since that is the label they give that group and therefore the easiest way for them to identify the group.

**Comment by forresttanaka** [comment] 2015-07-23 21:53
* I see what yo mean about the text in the gray box. Will try to work something out; might be bolding, color, etc.
* I’ll add a pipe there. The last task before PRing this Issue is to implement editing this group. Hoping to finish tomorrow, but it does have some tricks (e.g. create a method if none exists, but modify if it does).

**Comment by forresttanaka** [comment] 2015-07-23 22:09
This is the View page. Wasn’t sure if you needed a palette to the right, and what it should allow if there is one. This takes the entire page width as it stands.

![screen shot 2015-07-23 at 15 08 12](https://cloud.githubusercontent.com/assets/1181324/8863352/ad58bf94-314c-11e5-86c2-c84e277e80ff.png)

**Comment by kgliu0101** [comment] 2015-07-23 22:25
I see all values correct here, cool

**Comment by forresttanaka** [comment] 2015-07-23 22:32
Forgot to mention I need a way for people to return to Curation Central from the View page, so that’ll happen through the URL query string. I’ll need to add a button somewhere on the page.

**Comment by selinad** [comment] 2015-07-23 22:45
So cool - this is real!

There are a few fields I don't see, but maybe it's just because you didn't enter anything? e.g.
* Phenotype (HPO)
* Phenotype (free text)
* Country of Origin
* Ethnicity
* Age information
* **Section** for Additional information (including additional PMIDs)

What happens when you either + (add new Group) or View or Edit a group?  Do you open up a new page or just go to a different page that replaces curation central? (i.e. replace the left menu and abstract with this?).  This will help me answer the question you have.  I'm thinking most people will already have opened the paper up in a different window, so might be nice to do the latter.  Let me know if it's easier to talk.

**Comment by selinad** [comment] 2015-07-23 22:46
p.s. after one submits Group info, there are choices, so won't go directly back to Curation Central.

**Comment by forresttanaka** [comment] 2015-07-23 22:48
Yes, any fields that don’t have a value in the group object don’t appear at all in the View Group page.

Adding a group takes you to an Add Group page where you enter lots of info. Viewing a page takes you to the page whose screenshot I posted. Edit Group takes you to a page just like Add Group.

**Comment by selinad** [comment] 2015-07-23 22:48
@forresttanaka - would it help or complicate to make edit and view go to the same place, at least for 0.5? That way, you can use the form, but already entered items will have a value?  Have no clue what is easier.

**Comment by selinad** [comment] 2015-07-23 23:08
Forrest and I talked since I had missed that this was the View not the results of Submit (my bad)- here are conclusions:
* Clicking on new group gives whole new page without the right navigation as we want to guide users through a process
* there will be options after submission about where to go, as is on the pptx
* View and Edit are distinct - will need way to get back to central after viewing.

**Comment by selinad** [comment] 2015-07-23 23:10
Another conclusion:
* will include field titles even if empty on the View - curator might want to be reminded of what they missed.

**Comment by forresttanaka** [comment] 2015-07-24 22:08
Now taking owner into account. Clicking an article you’re not the owner of disables adding or editing a group.

![group-enabled](https://cloud.githubusercontent.com/assets/1181324/8885554/aee4a6b0-3215-11e5-9533-9597c96c8792.gif)

**Comment by selinad** [comment] 2015-07-24 22:31
Hey Forrest - this looks right given the limited functionality of 0.5 (that is, the ability of 2 curators to add evidence to the same paper).  We will need to create some feedback for curators as to why they can't edit an article they haven't added to the record.  The question is whether to spell that out clearly in some sort of initial help document, and/or to provide feedback directly on the page.  It's tricky, because this will change for 1.0, so we'd almost have to say that (or maybe say "currently, only the curator who adds a paper to a Gene-Disease record can associate evidence with that paper").  Is there a best practices for a beta version?

**Comment by forresttanaka** [comment] 2015-07-24 22:34
@kgliu0101 and I were talking about adding a line each item on the PMID list on the left that shows the owner email and maybe the creation date.

**Comment by selinad** [comment] 2015-07-24 22:45
Something like this might be ok, but I'm afraid it will ruin the simple look if email address, date etc. is added.  

Another option - put it below the abstract? (ie. so it's not in the left column).  I guess it might be cool to put "Added by: username" on the left side at some point. 

Forrest and I just talked about adding a note that lets a curator understand why they can't add evidence for a paper they haven't added - for now, if it's easy and you want to put the person who added it in there, maybe right below that note....?

**Comment by forresttanaka** [comment] 2015-07-24 22:49
How about we (meaning “how about @selinad?”) make a new ticket for identifying the paper’s owner, and get that merged separately from this ticket? Or is it pretty fundamental to this ticket?

**Comment by selinad** [comment] 2015-07-24 23:00
I am happy to make a ticket, whatever works best for you.  Should I include the addition of the note with that ticket since it is related?  I will say that only the note is critical for 0.5, so if it is a time consuming feature to associate the paper's owner, let's forgo it for now (it's not as important as getting Family pages up, for instance).

**Comment by forresttanaka** [comment] 2015-07-24 23:08
Discussed with @selinad; will add both The Note and the paper’s owner in this ticket, only appearing when you select a paper you didn’t add.

**Comment by forresttanaka** [comment] 2015-07-24 23:19
Displayed when a paper not added by the currently logged-in user is selected. Nothing appears in the italicized area if a paper added by the currently logged-in user is selected.

![screen shot 2015-07-24 at 16 18 12](https://cloud.githubusercontent.com/assets/1181324/8886474/a74cb87a-321f-11e5-8e4d-8b01bb14167d.png)

**Comment by selinad** [comment] 2015-07-24 23:21
Looks good, Forrest.  Minor thing.  If you are going to include the PMID, then I would format it as we do elsewhere: 

*PMID:7847369 added by tsneddon@stanford.edu*

**Comment by forresttanaka** [comment] 2015-07-24 23:27
In preparation for a PR for this ticket:

* Made /group-curation page functional. Values entered on the form are checked for validity, required-ness, and availability in our database in the case of fields that take genes, PMIDs, and diseases.
* The curator palette on the /curation-central page now takes users to the group curation page with the current GDM and annotation UUIDs in the query string. Clicking “Save” at the bottom of the form saves the group.json object, as well as the method.json object if needed.
* Group editing now implmented by bringing up the same page as creating a group, but with existing group values already filled in.
* Viewing a group now implemented. It comes up in a separate window when View is clicked in the Curator Palette.
* The contents of the Curator Palette now reacts to the owner of each PubMed paper. If the logged-in user clicks on a paper added by another user, the Palette grays out the Group Add button, and any existing groups show they can be viewed but not edited.
* For 0.5, added a note to the /curation-central page, between the PubMed summary and its abstract, so that testers know that they cannot curate a paper they haven’t added.

**Comment by forresttanaka** [comment] 2015-07-24 23:56
Was just seeing if I could make an AWS instance at all, but I’ll leave it up for a while if you’d like to give it a try.

**Comment by selinad** [comment] 2015-07-25 00:21
Hey, cool!  I was able to get it to work!  Not sure how much testing you want me to do right now. Initial observations:

* would not take list of gene names, comma separated, but would take 1 gene name
* would not take PMID - I tried 12345678, which I was later able to add to record (although it prints out funny as there are no authors (I can make a 1.0 tag for this - it will be rare): 

". Denpasar Declaration on Population and Development. Integration (Tokyo, Japan). 1994-May;(40):27-9" 

I also tried adding other PMIDs and they would not submit

* There is a problem in that if there is an error way up on the page, it looks like it's not submitting because one can't see the error - so, when I couldn't enter a gene name, I first thought the problem was that the page was not submitting...but the error was out of my window view.  Suggestion: put a phrase next to Submit button when there is an error - e.g. "Please fix error(s) and resubmit"  At least this way users will know that an error is causing what looks instead to be a lack response.

* I may have a few more wording changes for Group page - have not heard back re Disease and Phenotype yet, so will update to what I think is correct.  It will be fine for 0.5.

* Is this synced with History section?  e.g. I think the entry under History should say "Group added" or "added Group" rather than "added" as it does now....should I add a new ticket for that?

**Comment by forresttanaka** [comment] 2015-07-27 15:23
PMID 12345678 has an AuthorList format that the PubMed parsing code I imported doesn’t handle. I submitted https://github.com/ClinGen/clincoded/issues/128 for this.

**Comment by forresttanaka** [comment] 2015-07-27 15:45
@selinad 

Could you follow-up on some of your Friday’s feedback? My feedback-feedback:

* It’s taking a list of gene names, comma separated for me. Could you put together a reproducible sequence to replicate? I added AGTR2 and CDIP1 to [this one](http://6-ft-group-curation-dd85bfd-fytanaka.instance.clinicalgenome.org/groups/4ce5532f-b109-480a-9544-ce3023a873ba/).
* This is a bug that I put into a new Issue in the last comment I made.
* I’ll add a note next to the button and add it to this Issue’s PR.
* On wording changes, submit a new issue once those come in, unless you get them while this issue is still open (pre-PR-merge).
* This probably needs a new issue. This is on the Dashboard I think?

**Comment by forresttanaka** [comment] 2015-07-27 17:12
New instance, with clean test data right now:

http://6-ft-group-curation-f483f44-fytanaka.instance.clinicalgenome.org/

**Comment by selinad** [comment] 2015-07-27 17:53
Hi @forresttanaka - would not submit - here is screenshot

![screen shot 2015-07-27 at 10 52 52 am](https://cloud.githubusercontent.com/assets/11320314/8913391/b64b1c88-344d-11e5-884f-e5401cd75c62.png)

**Comment by selinad** [comment] 2015-07-27 18:33
Wording changes, etc.:

1. Group name: (clarification) this is mandatory for 0.5, but will not be required in later versions, correct?
1. "Orphanet common diagnosis" -> "Disease in Common (Orphanet term)"
* put example in box, e.g. ORPHA15
* "Orphanet" will be linked as is currently linked
1. "HPO ID(s)" -> "Shared Phenotypes (HPO ID(s)); PhenExplorer)"
* put example HPO terms in box, e.g. HP:0010704, HP:0030300
* "HPO" is not linked, but now "PhenExplorer" has the link 
1. "Free text phenotype terms" -> "Shared Phenotype(s) (free text)"
1. "NOT HPO ID(s)" -> "NOT Phenotype(s) (HPO ID(s); PhenExplorer)"
* "HPO" is not linked, but now "PhenExplorer" has the link 
* put example HPO terms in box, e.g. HP:0010704, HP:0030300
1. Free text NOT phenotype terms ->  "Not Phenotype(s) (free text)"
1. "Other genes found to have variants in them
* add example in box, e.g. DICER1, SMAD3
* would be great to have HGNC link somewhere here, but OK if not trivial (let me know) - something like "Other genes found to have variants in them (HGNC symbol)" <- with HGNC linked.
1. "Enter PMID(s) that report evidence about this same group
* add example in box, e.g. 21352784, 21657890  (I typed these randomly, so you may want to pick specific ones from the test data)

Let me know if there is anything in here that is not trivial to change.

thanks!
Selina

**Comment by selinad** [comment] 2015-07-27 18:42
@forresttanaka, the error feedback works well.  Were you going to make HPO terms be of a certain format?  e.g. HP:NNNNNNN - I think they are all HP: followed by 7 numbers.

**Comment by forresttanaka** [comment] 2015-07-27 18:43
@selinad I can add testing for HP:NNNNNNN; it’s not too hard.

**Comment by selinad** [comment] 2015-07-27 19:04
This would be helpful in reducing entry errors until we have the HPO terms loaded (later version).  @forresttanaka , do you need an error message to show?  

e.g.
HPO IDs must be in the format "HP:NNNNNNN," where N is a digit
(or something like that - perhaps you have a best practice way)

**Comment by forresttanaka** [comment] 2015-07-27 19:06
That sounds good. Nice reformatting of the earlier comment!

**Comment by forresttanaka** [comment] 2015-07-28 15:16
FYI, I think the right way to go on the group curation page is to have the little navigation area on the left as in the PPT. The method I use is easier to code, but harder to use, and I’d like to look at moving it to some form of the one in the PPT after 0.5 some time. Need to decide whether the navigation swaps panels in as each item is clicked, or scrolls to an already-visible panel.

**Comment by selinad** [comment] 2015-07-28 16:36
Hi Forrest - I may be a little confused.  You would like to add the left-hand article list to the Group page?  This could be a little confusing as the Group page is specific to one article.  We can chat tomorrow so I make sure I understand what you are suggesting.

**Comment by forresttanaka** [comment] 2015-07-28 16:39
@selinad No, the little navigation area that lets you choose which panel to see (Demographics, Additional Information, Method, etc.). It’s on the left of your PPT on the Group Curation pages.

**Comment by selinad** [comment] 2015-07-28 16:44
ohhh....  Yes, that makes sense.  I think the left nav functionality would be nicer for a later version.  SGD uses it, if that helps you with coding - e.g. http://www.yeastgenome.org/locus/S000005493/overview

There is also a back to top button that displays on the lower right once you start scrolling - I don't find it that obvious, but it is a great functionality to have when you get used to it.

**Comment by forresttanaka** [comment] 2015-07-28 17:26
This isn’t *quite* the same version as in the PR https://github.com/ClinGen/clincoded/pull/139; a couple merges came in afterwards. But it should work the same.

http://6-ft-group-curation-a72d3b5-fytanaka.instance.clinicalgenome.org/dashboard/

**Comment by selinad** [comment] 2015-07-28 18:56
Hi @forresttanaka - 

looking great - the e.g.s are very helpful.

A few items:
* there is an extra parentheses after HPO ID(s) (right now reads: (HPO ID(s)); PhenExplorer)
* Should have thought to ask - could the parentheses and part inbetween them be in regular font?  Not worth it for 0.5 unless a 10 minute fix (I think it will be longer than that given what you mentioned about styling yesterday, so no biggie)
* NOT used to be red and I thought we were going to keep?
* The last field in the first section - says "Not" rather than NOT and is 'not' in red.

Have 2 meetings now, but will test again after....

**Comment by forresttanaka** [comment] 2015-07-28 19:09
Close the PR again to integrate @selinad latest.

* I should have asked about the extra parens; that did look strange to me.
* “regular font” means not bold?
* Forgot all about the red grr.
* Ah, I should have asked about that too.

**Comment by forresttanaka** [comment] 2015-07-28 21:10
Check parens and things; I’m actually not at all sure how they’re supposed to go:

![screen shot 2015-07-28 at 14 09 22](https://cloud.githubusercontent.com/assets/1181324/8943931/5d9b2994-3532-11e5-88aa-953afb6294e7.png)

**Comment by selinad** [comment] 2015-07-28 21:36
Thanks for fixing up the styling!

Here is how the Shared Phenotypes and the NOT Phenotypes lines should read:

**Shared Phenotype(s)** (HPO ID(s); PhenExplorer):

**NOT Phenotype(s)** (HPO ID(s); PhenExplorer):  (with NOT in red, as is)

**Comment by kilodalton** [comment] 2015-10-31 23:56
Great job. Thanks for all your hard work to get the app to production!

**Closed by kilodalton** 2015-10-31 23:56 UTC
Labels: merged, new UI feature, v0.5
